In [26]:
import importlib
import pandas as pd
import fetch_diavgeia as fd


importlib.reload(fd)

df = pd.read_csv("../data/2026_diavgeia.csv")
df2 = fd.enrich_dataframe(df)
df2.head()

,ada,protocolNumber,issueDate,submissionTimestamp,publishTimestamp,status,nonRevokable,documentUrl,subject,documentType,versionComment,decisionType,thematicCategories,organization,cooperatingOrganizations,unitIds,org,org_type,org_name_clean
0,ΡΗΠΒΩ6Ι-ΒΛΒ,2312/24/2026,18/02/2026 02:00:00,18/02/2026 12:41:54,18/02/2026 12:41:54,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΡΗΠΒΩ6Ι-ΒΛΒ,Διαμόρφωση προϋπολογισμού του Δήμου Αγιάς έτου...,ΠΡΑΞΗ,NaN,ΛΟΙΠΕΣ ΑΤΟΜΙΚΕΣ ΔΙΟΙΚΗΤΙΚΕΣ ΠΡΑΞΕΙΣ,[ΔΗΜΟΣΙΟΝΟΜΙΚΑ],"{'uid': '6003', 'label': 'ΔΗΜΟΣ ΑΓΙΑΣ', 'activ...",NaN,['83352'],ΔΗΜΟΣ ΑΓΙΑΣ,ΔΗΜΟΣ,ΑΓΙΑΣ
1,Ψ7ΦΑ4653Π8-Τ98,59413,18/02/2026 02:00:00,18/02/2026 12:26:32,18/02/2026 12:26:32,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/Ψ7ΦΑ4653Π8-Τ98,Έγκριση της 1ης Αναλυτικής Επιμέτρησης των εργ...,ΠΡΑΞΗ,NaN,ΛΟΙΠΕΣ ΑΤΟΜΙΚΕΣ ΔΙΟΙΚΗΤΙΚΕΣ ΠΡΑΞΕΙΣ,"[ΓΕΩΡΓΙΑ, ΔΑΣΟΚΟΜΙΑ ΚΑΙ ΑΛΙΕΙΑ]","{'uid': '100015996', 'label': 'ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒ...",NaN,NaN,ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ,ΥΠΟΥΡΓΕΙΟ,ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ
2,9ΚΠΣΩ1Ε-ΕΑ0,3497 - 18-02-2026,18/02/2026 02:00:00,18/02/2026 11:38:36,18/02/2026 11:38:36,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/9ΚΠΣΩ1Ε-ΕΑ0,Απόφαση Ανάληψης Υποχρέωσης Α-271 για :Προμήθε...,ΠΡΑΞΗ,NaN,ΑΝΑΛΗΨΗ ΥΠΟΧΡΕΩΣΗΣ,[ΔΗΜΟΣΙΑ ΔΙΟΙΚΗΣΗ],"{'uid': '6266', 'label': 'ΔΗΜΟΣ ΣΑΛΑΜΙΝΑΣ', 'a...",NaN,NaN,ΔΗΜΟΣ ΣΑΛΑΜΙΝΑΣ,ΔΗΜΟΣ,ΣΑΛΑΜΙΝΑΣ
3,9449Ω1Ε-Ν9Π,3495 - 18-02-2026,18/02/2026 02:00:00,18/02/2026 11:36:10,18/02/2026 11:36:10,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/9449Ω1Ε-Ν9Π,Απόφαση Ανάληψης Υποχρέωσης Α-269 για :Ενίσχυσ...,ΠΡΑΞΗ,NaN,ΑΝΑΛΗΨΗ ΥΠΟΧΡΕΩΣΗΣ,[ΔΗΜΟΣΙΑ ΔΙΟΙΚΗΣΗ],"{'uid': '6266', 'label': 'ΔΗΜΟΣ ΣΑΛΑΜΙΝΑΣ', 'a...",NaN,NaN,ΔΗΜΟΣ ΣΑΛΑΜΙΝΑΣ,ΔΗΜΟΣ,ΣΑΛΑΜΙΝΑΣ
4,ΨΠ54ΩΚΥ-ΨΨΡ,70,17/02/2026 02:00:00,18/02/2026 09:11:28,18/02/2026 09:11:28,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΨΠ54ΩΚΥ-ΨΨΡ,Κατάρτιση και ψήφιση προϋπολογισμού του Δήμου ...,ΠΡΑΞΗ,NaN,ΕΓΚΡΙΣΗ ΠΡΟΥΠΟΛΟΓΙΣΜΟΥ,[ΟΙΚΟΝΟΜΙΚΗ ΖΩΗ],"{'uid': '6209', 'label': 'ΔΗΜΟΣ ΝΕΑΣ ΙΩΝΙΑΣ', ...",NaN,NaN,ΔΗΜΟΣ ΝΕΑΣ ΙΩΝΙΑΣ,ΔΗΜΟΣ,ΝΕΑΣ ΙΩΝΙΑΣ

In [27]:
df.tail()

,ada,protocolNumber,issueDate,submissionTimestamp,publishTimestamp,status,nonRevokable,documentUrl,subject,documentType,versionComment,decisionType,thematicCategories,organization,cooperatingOrganizations,unitIds,org,org_type,org_name_clean
22965,9ΒΒΖ4653Π8-ΞΑ3,59762,18/02/2026 02:00:00,18/02/2026 13:51:30,18/02/2026 13:51:30,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/9ΒΒΖ4653Π8-ΞΑ3,Έγκριση πρώτου 1ου Ειδικού Απολογισμού και Με...,ΠΡΑΞΗ,NaN,"{'uid': 'Α.2', 'label': 'ΚΑΝΟΝΙΣΤΙΚΗ ΠΡΑΞΗ'}","[{'uid': '52', 'label': 'ΠΕΡΙΒΑΛΛΟΝ'}]","{'uid': '100015996', 'label': 'ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒ...",NaN,NaN,ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ,ΥΠΟΥΡΓΕΙΟ,ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ
22966,650ΓΩΡΗ-Υ1Τ,1060,18/02/2026 02:00:00,18/02/2026 13:49:04,18/02/2026 13:49:04,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/650ΓΩΡΗ-Υ1Τ,Ψήφιση και έγκριση προϋπολογισμού του Δήμου Ζα...,ΠΡΑΞΗ,NaN,"{'uid': 'Β.1.1', 'label': 'ΕΓΚΡΙΣΗ ΠΡΟΥΠΟΛΟΓΙΣ...","[{'uid': '24', 'label': 'ΔΗΜΟΣΙΟΝΟΜΙΚΑ'}]","{'uid': '6101', 'label': 'ΔΗΜΟΣ ΖΑΧΑΡΩΣ', 'act...",NaN,NaN,ΔΗΜΟΣ ΖΑΧΑΡΩΣ,ΔΗΜΟΣ,ΖΑΧΑΡΩΣ
22967,ΡΥΠΞΩΞ2-1ΝΓ,63/18-2-2026,18/02/2026 02:00:00,18/02/2026 13:36:14,18/02/2026 13:36:14,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΡΥΠΞΩΞ2-1ΝΓ,Έγκριση έκθεσης πεπραγμένων Β’ Εξαμήνου 2025 τ...,ΠΡΑΞΗ,NaN,"{'uid': '2.4.7.1', 'label': 'ΛΟΙΠΕΣ ΑΤΟΜΙΚΕΣ Δ...","[{'uid': '10004', 'label': 'ΔΗΜΟΣΙΑ ΔΙΟΙΚΗΣΗ'}]","{'uid': '6247', 'label': 'ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ', ...",NaN,NaN,ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ,ΔΗΜΟΣ,ΠΕΡΙΣΤΕΡΙΟΥ
22968,942ΛΩΞ2-ΟΘΔ,15,17/02/2026 02:00:00,18/02/2026 13:35:47,18/02/2026 13:35:47,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/942ΛΩΞ2-ΟΘΔ,"Έγκριση Προϋπολογισμού του Δήμου, έτους 2026.",ΠΡΑΞΗ,NaN,"{'uid': 'Β.1.1', 'label': 'ΕΓΚΡΙΣΗ ΠΡΟΥΠΟΛΟΓΙΣ...","[{'uid': '16', 'label': 'ΟΙΚΟΝΟΜΙΚΗ ΖΩΗ'}]","{'uid': '6247', 'label': 'ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ', ...",NaN,NaN,ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ,ΔΗΜΟΣ,ΠΕΡΙΣΤΕΡΙΟΥ
22969,ΡΞΞ97ΛΛ-ΑΟΛ,46833/35,05/02/2026 02:00:00,18/02/2026 13:35:09,18/02/2026 13:35:09,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΡΞΞ97ΛΛ-ΑΟΛ,Γνωμοδότηση επί της Μελέτης Περιβαλλοντικών Επ...,ΠΡΑΞΗ,NaN,"{'uid': 'Α.2', 'label': 'ΚΑΝΟΝΙΣΤΙΚΗ ΠΡΑΞΗ'}","[{'uid': '52', 'label': 'ΠΕΡΙΒΑΛΛΟΝ'}]","{'uid': '5009', 'label': 'ΠΕΡΙΦΕΡΕΙΑ ΚΕΝΤΡΙΚΗΣ...",NaN,NaN,ΠΕΡΙΦΕΡΕΙΑ ΚΕΝΤΡΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ,ΠΕΡΙΦΕΡΕΙΑ,ΚΕΝΤΡΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ