In [ ]:
import importlib
import pandas as pd
import fetch_diavgeia as fd
pd.set_option('display.max_columns', None)

In [220]:
df = pd.read_csv("../data/2026_diavgeia.csv")

In [221]:
df.tail()

,ada,protocolNumber,issueDate,submissionTimestamp,publishTimestamp,status,nonRevokable,documentUrl,subject,documentType,versionComment,decisionType,thematicCategories,organization,cooperatingOrganizations,unitIds,org,org_type,org_name_clean,spending_signers,spending_contractors_afm,spending_contractors_name,spending_contractors_value,spending_contractors_currency,spending_contractors_count,spending_contractors_details,spending_enrichment_status,spending_enrichment_error,commitment_signers,commitment_fiscal_year,commitment_budget_category,commitment_counterparty,commitment_amount_with_vat,commitment_remaining_available_credit,commitment_kae_ale_number,commitment_remaining_kae_ale,commitment_lines_count,commitment_lines_details,commitment_enrichment_status,commitment_enrichment_error,direct_signers,direct_afm,direct_name,direct_value,direct_related_commitment,direct_see_also,direct_people_count,direct_people_details,direct_enrichment_status,direct_enrichment_error,payment_signers,payment_beneficiary_afm,payment_beneficiary_name,payment_value,payment_related_commitment_or_spending,payment_see_also,payment_beneficiaries_count,payment_beneficiaries_details,payment_enrichment_status,payment_enrichment_error,subject_has_keyword,subject_match,pdf_match,pdf_available_for_filter,is_relevant,matched_keywords_subject,matched_keywords_pdf
22965,9ΒΒΖ4653Π8-ΞΑ3,59762,18/02/2026 02:00:00,18/02/2026 13:51:30,18/02/2026 13:51:30,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/9ΒΒΖ4653Π8-ΞΑ3,Έγκριση πρώτου 1ου Ειδικού Απολογισμού και Με...,ΠΡΑΞΗ,NaN,ΚΑΝΟΝΙΣΤΙΚΗ ΠΡΑΞΗ,['ΠΕΡΙΒΑΛΛΟΝ'],"{'uid': '100015996', 'label': 'ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒ...",NaN,NaN,ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ,ΥΠΟΥΡΓΕΙΟ,ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,True,αντιπυρ,"['αντιπυρ', 'δασικου οδικου δικτυου', 'ΠΡΟΣΤΑΣ..."
22966,650ΓΩΡΗ-Υ1Τ,1060,18/02/2026 02:00:00,18/02/2026 13:49:04,18/02/2026 13:49:04,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/650ΓΩΡΗ-Υ1Τ,Ψήφιση και έγκριση προϋπολογισμού του Δήμου Ζα...,ΠΡΑΞΗ,NaN,ΕΓΚΡΙΣΗ ΠΡΟΥΠΟΛΟΓΙΣΜΟΥ,['ΔΗΜΟΣΙΟΝΟΜΙΚΑ'],"{'uid': '6101', 'label': 'ΔΗΜΟΣ ΖΑΧΑΡΩΣ', 'act...",NaN,NaN,ΔΗΜΟΣ ΖΑΧΑΡΩΣ,ΔΗΜΟΣ,ΖΑΧΑΡΩΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,True,True,Προϋπολογισμού,"['πυροπροστ', 'αντιπυρ', 'δασικου οδικου δικτυ..."
22967,ΡΥΠΞΩΞ2-1ΝΓ,63/18-2-2026,18/02/2026 02:00:00,18/02/2026 13:36:14,18/02/2026 13:36:14,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΡΥΠΞΩΞ2-1ΝΓ,Έγκριση έκθεσης πεπραγμένων Β’ Εξαμήνου 2025 τ...,ΠΡΑΞΗ,NaN,ΛΟΙΠΕΣ ΑΤΟΜΙΚΕΣ ΔΙΟΙΚΗΤΙΚΕΣ ΠΡΑΞΕΙΣ,['ΔΗΜΟΣΙΑ ΔΙΟΙΚΗΣΗ'],"{'uid': '6247', 'label': 'ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ', ...",NaN,NaN,ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ,ΔΗΜΟΣ,ΠΕΡΙΣΤΕΡΙΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,True,True,True,NaN,"['πυροπροστ', 'αντιπυρ', 'δασικων πυρκαγιων', ..."
22968,942ΛΩΞ2-ΟΘΔ,15,17/02/2026 02:00:00,18/02/2026 13:35:47,18/02/2026 13:35:47,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/942ΛΩΞ2-ΟΘΔ,"Έγκριση Προϋπολογισμού του Δήμου, έτους 2026.",ΠΡΑΞΗ,NaN,ΕΓΚΡΙΣΗ ΠΡΟΥΠΟΛΟΓΙΣΜΟΥ,['ΟΙΚΟΝΟΜΙΚΗ ΖΩΗ'],"{'uid': '6247', 'label': 'ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ', ...",NaN,NaN,ΔΗΜΟΣ ΠΕΡΙΣΤΕΡΙΟΥ,ΔΗΜΟΣ,ΠΕΡΙΣΤΕΡΙΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,True,True,Προϋπολογισμού,"['πυροπροστ', 'αντιπυρ', 'δασικων πυρκαγιων', ..."
22969,ΡΞΞ97ΛΛ-ΑΟΛ,46833/35,05/02/2026 02:00:00,18/02/2026 13:35:09,18/02/2026 13:35:09,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΡΞΞ97ΛΛ-ΑΟΛ,Γνωμοδότηση επί της Μελέτης Περιβαλλοντικών Επ...,ΠΡΑΞΗ,NaN,ΚΑΝΟΝΙΣΤΙΚΗ ΠΡΑΞΗ,['ΠΕΡΙΒΑΛΛΟΝ'],"{'uid': '5009', 'label': 'ΠΕΡΙΦΕΡΕΙΑ ΚΕΝΤΡΙΚΗΣ...",NaN,NaN,ΠΕΡΙΦΕΡΕΙΑ ΚΕΝΤΡΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ,ΠΕΡΙΦΕΡΕΙΑ,ΚΕΝΤΡΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,True,True,True,NaN,"['πυροπροστ', 'αποψιλ', 'δασοπροστ', 'αντιπυρ'..."

In [222]:
set(df.decisionType.tolist())

{'ΑΘΩΩΤΙΚΗ ΠΕΙΘΑΡΧΙΚΗ ΑΠΟΦΑΣΗ',
 'ΑΛΛΗ ΠΡΑΞΗ ΑΝΑΠΤΥΞΙΑΚΟΥ ΝΟΜΟΥ',
 'ΑΝΑΘΕΣΗ ΕΡΓΩΝ / ΠΡΟΜΗΘΕΙΩΝ / ΥΠΗΡΕΣΙΩΝ / ΜΕΛΕΤΩΝ',
 'ΑΝΑΛΗΨΗ ΥΠΟΧΡΕΩΣΗΣ',
 'ΑΠΟΦΑΣΗ ΕΝΑΡΞΗΣ ΠΑΡΑΓΩΓΙΚΗΣ ΛΕΙΤΟΥΡΓΙΑΣ ΕΠΕΝΔΥΣΗΣ',
 'ΓΝΩΜΟΔΟΤΗΣΗ',
 'ΔΗΜΟΣΙΑ ΠΡΟΤΥΠΑ ΕΓΓΡΑΦΑ',
 'ΔΙΟΡΙΣΜΟΣ',
 'ΔΩΡΕΑ - ΕΠΙΧΟΡΗΓΗΣΗ',
 'ΕΓΚΡΙΣΗ ΔΑΠΑΝΗΣ',
 'ΕΓΚΡΙΣΗ ΠΡΟΥΠΟΛΟΓΙΣΜΟΥ',
 'ΕΓΚΥΚΛΙΟΣ',
 'ΕΠΙΤΡΟΠΙΚΟ ΕΝΤΑΛΜΑ',
 'ΙΣΟΛΟΓΙΣΜΟΣ – ΑΠΟΛΟΓΙΣΜΟΣ',
 'ΚΑΝΟΝΙΣΤΙΚΗ ΠΡΑΞΗ',
 'ΚΑΤΑΚΥΡΩΣΗ',
 'ΛΟΙΠΕΣ ΑΤΟΜΙΚΕΣ ΔΙΟΙΚΗΤΙΚΕΣ ΠΡΑΞΕΙΣ',
 'ΝΟΜΟΣ',
 'ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΠΛΗΡΩΜΗΣ',
 'ΠΑΡΑΧΩΡΗΣΗ ΧΡΗΣΗΣ ΠΕΡΙΟΥΣΙΑΚΩΝ ΣΤΟΙΧΕΙΩΝ',
 'ΠΕΡΙΛΗΨΗ ΔΙΑΚΗΡΥΞΗΣ',
 'ΠΕΡΙΛΗΨΗ ΔΙΑΚΗΡΥΞΗΣ / ΔΙΑΚΗΡΥΞΗ (ΑΠΟ 1.10.2025)',
 'ΠΙΝΑΚΕΣ ΕΠΙΤΥΧΟΝΤΩΝ, ΔΙΟΡΙΣΤΕΩΝ & ΕΠΙΛΑΧΟΝΤΩΝ',
 'ΠΡΑΞΕΙΣ ΧΩΡΟΤΑΞΙΚΟΥ - ΠΟΛΕΟΔΟΜΙΚΟΥ ΠΕΡΙΕΧΟΜΕΝΟΥ',
 'ΠΡΑΞΗ ΠΟΥ ΑΦΟΡΑ ΣΕ ΘΕΣΗ ΓΕΝΙΚΟΥ - ΕΙΔΙΚΟΥ ΓΡΑΜΜΑΤΕΑ - ΜΟΝΟΜΕΛΕΣ ΟΡΓΑΝΟ',
 'ΠΡΑΞΗ ΠΟΥ ΑΦΟΡΑ ΣΕ ΣΥΛΛΟΓΙΚΟ ΟΡΓΑΝΟ - ΕΠΙΤΡΟΠΗ - ΟΜΑΔΑ ΕΡΓΑΣΙΑΣ - ΟΜΑΔΑ ΕΡΓΟΥ - ΜΕΛΗ ΣΥΛΛΟΓΙΚΟΥ ΟΡΓΑΝΟΥ',
 'ΠΡΟΚΗΡΥΞΗ ΠΛΗΡΩΣΗΣ ΘΕΣΕΩΝ',
 'ΣΥΜΒΑΣΗ',
 'ΣΥΜΒΑΣΗ-ΠΡΑΞΕΙΣ ΑΝΑΠΤΥΞΙΑΚΩΝ ΝΟΜΩΝ'}

In [223]:
df[df.decisionType=="ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΠΛΗΡΩΜΗΣ"]

,ada,protocolNumber,issueDate,submissionTimestamp,publishTimestamp,status,nonRevokable,documentUrl,subject,documentType,versionComment,decisionType,thematicCategories,organization,cooperatingOrganizations,unitIds,org,org_type,org_name_clean,spending_signers,spending_contractors_afm,spending_contractors_name,spending_contractors_value,spending_contractors_currency,spending_contractors_count,spending_contractors_details,spending_enrichment_status,spending_enrichment_error,commitment_signers,commitment_fiscal_year,commitment_budget_category,commitment_counterparty,commitment_amount_with_vat,commitment_remaining_available_credit,commitment_kae_ale_number,commitment_remaining_kae_ale,commitment_lines_count,commitment_lines_details,commitment_enrichment_status,commitment_enrichment_error,direct_signers,direct_afm,direct_name,direct_value,direct_related_commitment,direct_see_also,direct_people_count,direct_people_details,direct_enrichment_status,direct_enrichment_error,payment_signers,payment_beneficiary_afm,payment_beneficiary_name,payment_value,payment_related_commitment_or_spending,payment_see_also,payment_beneficiaries_count,payment_beneficiaries_details,payment_enrichment_status,payment_enrichment_error,subject_has_keyword,subject_match,pdf_match,pdf_available_for_filter,is_relevant,matched_keywords_subject,matched_keywords_pdf
5,ΡΚΣ2ΩΞΒ-ΜΤ7,ΧΕ 309/2026,17/02/2026 02:00:00,18/02/2026 09:06:06,17/02/2026 12:09:26,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΡΚΣ2ΩΞΒ-ΜΤ7,ΔΑΠΑΝΗ ΓΙΑ ΤΗΝ ΥΛΟΠΟΙΗΣΗ ΤΟΥ ΕΡΓΟΥ ΜΕ ΤΙΤΛΟ«ΔΗ...,ΠΡΑΞΗ,NaN,ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΠΛΗΡΩΜΗΣ,['ΟΙΚΟΝΟΜΙΚΕΣ ΚΑΙ ΕΜΠΟΡΙΚΕΣ ΣΥΝΑΛΛΑΓΕΣ'],"{'uid': '6225', 'label': 'ΔΗΜΟΣ ΟΡΕΣΤΙΑΔΑΣ', '...",NaN,NaN,ΔΗΜΟΣ ΟΡΕΣΤΙΑΔΑΣ,ΔΗΜΟΣ,ΟΡΕΣΤΙΑΔΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Αναπληρωτης Προϊστάμενος Τμήματος - ΠΑΛΛΙΔΗΣ Χ...,073720120,"ΕΠΙΣΚΕΠΤΗΣ,,ΙΩΑΝΝΗΣ,ΑΘΑΝΑΣΙΟΣ","51.879,31",NaN,NaN,1.0,"[{'ΑΦΜ': '073720120', 'Επωνυμία': 'ΕΠΙΣΚΕΠΤΗΣ,...",ok,NaN,True,True,True,True,True,"['αντιπυρ', 'δασικων πυρκαγιων']",αντιπυρ
14,ΨΔΚΜΩ93-Ε4Υ,11/26,17/02/2026 02:00:00,17/02/2026 12:04:08,17/02/2026 12:04:08,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΨΔΚΜΩ93-Ε4Υ,ΔΗΜΙΟΥΡΓΙΑ ΠΕΡΙΜΕΤΡΙΚΩΝ ΑΝΤΙΠΥΡΙΚΩΝ ΖΩΝΩΝ,ΠΡΑΞΗ,NaN,ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΠΛΗΡΩΜΗΣ,['ΟΙΚΟΝΟΜΙΚΕΣ ΚΑΙ ΕΜΠΟΡΙΚΕΣ ΣΥΝΑΛΛΑΓΕΣ'],"{'uid': '6075', 'label': 'ΔΗΜΟΣ ΔΙΟΝΥΣΟΥ', 'ac...",NaN,NaN,ΔΗΜΟΣ ΔΙΟΝΥΣΟΥ,ΔΗΜΟΣ,ΔΙΟΝΥΣΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Προϊστάμενος - ΠΑΝΟΤΟΠΟΥΛΟΣ ΠΑΝΑΓΙΩΤΗΣ,801520054,ΤΡΙΑ ΚΑΠΑ ΠΡΟΟΔΟΣ ΙΔΙΩΤΙΚΗ ΚΕΦΑΛΑΙΟΥΧΙΚΗ ΕΤΑΙΡΕΙΑ,"44.718,38",NaN,NaN,1.0,"[{'ΑΦΜ': '801520054', 'Επωνυμία': 'ΤΡΙΑ ΚΑΠΑ Π...",ok,NaN,True,True,True,True,True,αντιπυρ,"['πυροπροστ', 'αντιπυρ']"
15,9994Ω93-82Μ,10/26,17/02/2026 02:00:00,17/02/2026 11:41:46,17/02/2026 11:41:46,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/9994Ω93-82Μ,ΔΗΜΙΟΥΡΓΙΑ ΠΕΡΙΜΕΤΡΙΚΩΝ ΑΝΤΙΠΥΡΙΚΩΝ ΖΩΝΩΝ,ΠΡΑΞΗ,NaN,ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΠΛΗΡΩΜΗΣ,['ΟΙΚΟΝΟΜΙΚΕΣ ΚΑΙ ΕΜΠΟΡΙΚΕΣ ΣΥΝΑΛΛΑΓΕΣ'],"{'uid': '6075', 'label': 'ΔΗΜΟΣ ΔΙΟΝΥΣΟΥ', 'ac...",NaN,NaN,ΔΗΜΟΣ ΔΙΟΝΥΣΟΥ,ΔΗΜΟΣ,ΔΙΟΝΥΣΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Προϊστάμενος - ΠΑΝΟΤΟΠΟΥΛΟΣ ΠΑΝΑΓΙΩΤΗΣ,801520054,ΤΡΙΑ ΚΑΠΑ ΠΡΟΟΔΟΣ ΙΔΙΩΤΙΚΗ ΚΕΦΑΛΑΙΟΥΧΙΚΗ ΕΤΑΙΡΕΙΑ,"538,77",NaN,NaN,1.0,"[{'ΑΦΜ': '801520054', 'Επωνυμία': 'ΤΡΙΑ ΚΑΠΑ Π...",ok,NaN,True,True,True,True,True,αντιπυρ,"['πυροπροστ', 'αντιπυρ']"
19,6ΥΛΑΩ93-0Ν7,8/26,17/02/2026 02:00:00,17/02/2026 10:28:33,17/02/2026 10:28:33,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/6ΥΛΑΩ93-0Ν7,ΔΗΜΙΟΥΡΓΙΑ ΠΕΡΙΜΕΤΡΙΚΩΝ ΑΝΤΙΠΥΡΙΚΩΝ ΖΩΝΩΝ,ΠΡΑΞΗ,NaN,ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΠΛΗΡΩΜΗΣ,['ΟΙΚΟΝΟΜΙΚΕΣ ΚΑΙ ΕΜΠΟΡΙΚΕΣ ΣΥΝΑΛΛΑΓΕΣ'],"{'uid': '6075', 'label': 'ΔΗΜΟΣ ΔΙΟΝΥΣΟΥ', 'ac...",NaN,NaN,ΔΗΜΟΣ ΔΙΟΝΥΣΟΥ,ΔΗΜΟΣ,ΔΙΟΝΥΣΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Προϊστάμενος - ΠΑΝΟΤΟΠΟΥΛΟΣ ΠΑΝΑΓΙΩΤΗΣ,801520054,ΤΡΙΑ ΚΑΠΑ ΠΡΟΟΔΟΣ ΙΔΙΩΤΙΚΗ ΚΕΦΑΛΑΙΟΥΧΙΚΗ ΕΤΑΙΡΕΙΑ,"88.954,09",NaN,NaN,1.0,"[{'ΑΦΜ': '801520054', 'Επωνυμία': 'ΤΡΙΑ ΚΑΠΑ Π...",ok,NaN,True,True,True,True,True,αντιπυρ,"['πυροπροστ', 'αντιπυρ', 'ΠΕΡΙΜΕΤΡΙΚΩΝ ΖΩΝΩΝ']"
20,9ΚΟ1ΩΗΜ-6ΓΩ,65,16/02/2026 02:00:00,17/02/2026 09:45:56,17/02/2026 09:45:56,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/9ΚΟ1ΩΗΜ-6ΓΩ,ΣΕ ΑΝΤΙΚΑΤΑΣΤΑΣΗ ΤΟΥ ΑΚΥΡΩΜΕΝΟΥ ΚΑΙ ΜΗ ΕΞΟΦΛΗΜ...,ΠΡΑΞΗ,NaN,ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΠΛΗΡΩΜΗΣ,['ΟΙΚΟΝΟΜΙΚΕΣ ΚΑΙ ΕΜΠΟΡΙΚΕΣ ΣΥΝΑΛΛΑΓΕΣ'],"{'uid': '6319', 'label': 'ΔΗΜΟΣ ΧΕΡΣΟΝΗΣΟΥ', '...",NaN,NaN,ΔΗΜΟΣ ΧΕΡΣΟΝΗΣΟΥ,ΔΗΜΟΣ,ΧΕΡΣΟΝΗΣΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Αναπληρωτής Διευθυντής - ΣΚΥΒΑΛΑΚΗ ΘΕΟΝΥΜΦΗ,801355634,ΕΡΓΑ ΠΡΑΣΙΝΟΥ CANDIA GREEN O.E.,"35.959,94",NaN,NaN,1.0,"[{'ΑΦΜ': '801355634', 'Επωνυμία': 'ΕΡΓΑ ΠΡΑΣΙΝ...",ok,NaN,False,True,True,True,True,"['δημιουργια περιμετρικων ζωνων', 'ΠΕΡΙΜΕΤΡΙΚΩ...","['αντιπυρ', 'δημιουργια περιμετρικων ζωνων', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22900,ΨΞΩΥ4653Π8-ΡΓΘ,ΥΠΕΝ/ΕΠΛ/88783/294,13/08/2024 03:00:00,13/08/2024 13:37:57,13/08/2024 13:37:57,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΨΞΩΥ4653Π8-ΡΓΘ,Εκκαθάριση-εντολή πληρωμής της ΣΑ ΤΑ075 με τίτ...,ΠΡΑΞΗ,NaN,ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΠΛΗΡΩΜΗΣ,['ΟΙΚΟΝΟΜΙΚΕΣ ΚΑΙ ΕΜΠΟΡΙΚΕΣ ΣΥΝΑΛΛΑΓΕΣ'],"{'uid': '100015996', 'label': 'ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒ...",NaN,NaN,ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ,ΥΠΟΥΡΓΕΙΟ,ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Αναπληρωτής Προϊστάμενος Διεύθυνσης - ΖΩΓΟΠΟΥΛ...,NaN,NaN,"5.489.497,00",NaN,NaN,1.0,"[{'ΑΦΜ': None, 'Επωνυμία': None, 'Αξία': '5.48...",ok,NaN,False,False,True,True,True,NaN,"['δασοπροστ', 'αντιπυρ', 'δασικου οδικου δικτυ..."
22901,9Ν6ΦΩΗΝ-7ΧΖ,Α-205,27/06/2024 03:00:00,13/08/2024 13:24:23,13/08/2024 13:24:23,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/9Ν6ΦΩΗΝ-7ΧΖ,Χρηματικό Ενταλμα Πληρωμής Α-205 για :Καταβολή...,ΠΡΑΞΗ,NaN,ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΠΛΗΡΩΜΗΣ,['ΟΙΚΟΝΟΜΙΚΕΣ ΚΑΙ ΕΜΠΟΡΙΚΕΣ ΣΥΝΑΛΛΑΓΕΣ'],"{'uid': '6320', 'label': 'ΔΗΜΟΣ ΧΙΟΥ', 'active...",NaN,NaN,ΔΗΜΟΣ ΧΙΟΥ,ΔΗΜΟΣ,ΧΙΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ΑΝΩΓΙΑΝΝΑΚΗΣ ΝΙΚΟΛΑΟΣ,NaN,NaN,NaN,NaN,NaN,0.0,[],ok,NaN,False,False,True,True,True,NaN,"['πυροπροστ', 'ΠΥΡΑΣΦΑΛΕΙΑΣ']"
22909,6ΣΧΧΩΚΓ-1Ξ1,Β-1301,13/08/2024 03:00:00,13/08/2024 11:01:11,13/08/2024 11:01:11,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/6ΣΧΧΩΚΓ-1Ξ1,Χρηματικό Ενταλμα Πληρωμής Β-1301 για :Καθαρισ...,ΠΡΑΞΗ,NaN,ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΠΛΗΡΩΜΗΣ,['ΟΙΚΟΝΟΜΙΚΕΣ ΚΑΙ ΕΜΠΟΡΙΚΕΣ ΣΥΝΑΛΛΑΓΕΣ'],"{'uid': '6205', 'label': 'ΔΗΜΟΣ ΝΑΥΠΑΚΤΙΑΣ', '...",NaN,NaN,ΔΗΜΟΣ ΝΑΥΠΑΚΤΙΑΣ,ΔΗΜΟΣ,ΝΑΥΠΑΚΤΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Διευθυντής - ΚΟΥΚΟΥΝΑ ΠΑΡΑΣΚΕΥΗ,"['129031872', '129031872']","['ΚΑΖΑΝΑ ΕΛΕΝΗ Π.', 'ΚΑΖΑΝΑ ΕΛΕΝΗ Π.']","['2.807,86', '10.954,16']",NaN,"[{'Σχετικός ΑΔΑ': 'ΨΤΝΦΩΚΓ-ΒΥ2'}, {'Σχετικός Α...",2.0,"[{'ΑΦΜ': '129031872', 'Επωνυμία': 'ΚΑΖΑΝΑ ΕΛΕΝ...",ok,NaN,True,True,True,True,True,"['πυροπροστ', 'αποψιλ']","['πυροπροστ', 'αποψιλ']"
22924,6Κ75Ω97-3ΟΩ,Εντ.Α.2195.2024,12/08/2024 03:00:00,12/08/2024 12:53:57,12/08/2024 12:53:57,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/6Κ75Ω97-3ΟΩ,ΕΚΚΑΘΑΡΙΣΗ ΜΙΣΘΟΔΟΣΙΑΣ ΜΗΝΟΣ ΙΟΥΛΙΟΥ 2024 (ΠΥΡ...,ΠΡΑΞΗ,NaN,ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΠΛΗΡΩΜΗΣ,['ΟΙΚΟΝΟΜΙΚΕΣ ΚΑΙ ΕΜΠΟΡΙΚΕΣ ΣΥΝΑΛΛΑΓΕΣ'],"{'uid': '6056', 'label': 'ΔΗΜΟΣ ΒΟΙΟΥ', 'activ...",NaN,NaN,ΔΗΜΟΣ ΒΟΙΟΥ,ΔΗΜΟΣ,ΒΟΙΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Α/Α (Αντί Αυτού) Προϊσταμένου Τμήματος - ΜΗΤΡΟ...,NaN,NaN,"2.323,52",NaN,NaN,1.0,"[{'ΑΦΜ': None, 'Επωνυμία': None, 'Αξία': '2.32...",ok,NaN,True,True,True,True,True,πυροπροστ,πυροπροστ
22932,9ΟΨΩ4653Π8-ΙΦ5,ΥΠΕΝ/ΕΠΛ/87909/292,09/08/2024 03:00:00,09/08/2024 14:22:26,09/08/2024 14:22:26,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/9ΟΨΩ4653Π8-ΙΦ5,Εκκαθάριση-εντολή πληρωμής της ΣΑ ΤΑ075 με τίτ...,ΠΡΑΞΗ,NaN,ΟΡΙΣΤΙΚΟΠΟΙΗΣΗ ΠΛΗΡΩΜΗΣ,['ΟΙΚΟΝΟΜΙΚΕΣ ΚΑΙ ΕΜΠΟΡΙΚΕΣ ΣΥΝΑΛΛΑΓΕΣ'],"{'uid': '100015996', 'label': 'ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒ...",NaN,NaN,ΥΠΟΥΡΓΕΙΟ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ,ΥΠΟΥΡΓΕΙΟ,ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΙ ΕΝΕΡΓΕΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Διευθυντής - ΠΑΝΑΓΙΩΤΟΠΟΥΛΟΥ ΠΑΡΑΣΚΕΥΗ,NaN,NaN,"859.888,00",NaN,NaN,1.0,"[{'ΑΦΜ': None, 'Επωνυμία': None, 'Αξία': '859....",ok,NaN,False,False,True,True,True,NaN,"['δασοπροστ', 'αντιπυρ', 'ΠΡΟΣΤΑΣΙΑΣ ΔΑΣΩΝ', '..."

In [224]:
import requests
from urllib.parse import quote

ada = "ΨΓΠΑΩ15-ΗΣΡ"  # exact
url = f"https://diavgeia.gov.gr/luminapi/api/decisions/view/{quote(ada)}"

r = requests.get(url, timeout=30)
print(r.status_code, url)
r.json()

200 https://diavgeia.gov.gr/luminapi/api/decisions/view/%CE%A8%CE%93%CE%A0%CE%91%CE%A915-%CE%97%CE%A3%CE%A1

{'ada': 'ΨΓΠΑΩ15-ΗΣΡ',
 'publishTimestamp': '13/02/2026 12:15:28',
 'submissionTimestamp': '13/02/2026 12:15:28',
 'documentUrl': 'https://diavgeia.gov.gr/doc/ΨΓΠΑΩ15-ΗΣΡ',
 'meta': [{'Είδος': 'ΑΝΑΛΗΨΗ ΥΠΟΧΡΕΩΣΗΣ'},
  {'Θέμα': 'Σ.- Δημιουργία περιμετρικών αντιπυρικών ζωνών μέσου πλάτους 10 μέτρων πέριξ οικισμών εντός ή πλησίον δασών και δασικών εκτάσεων υψηλής επικινδυνότητας για την εκδήλωση δασικών πυρκαγιών στο Δήμο Σουφλίου-αρμοδιότητας Δασαρχείου Σουφλίου» με αρ. μελ. 49/2024.'},
  {'Θεματικές κατηγορίες': ['ΟΙΚΟΝΟΜΙΚΕΣ ΚΑΙ ΕΜΠΟΡΙΚΕΣ ΣΥΝΑΛΛΑΓΕΣ']},
  {'Αρ. πρωτοκόλλου': '2026/1417'},
  {'Ημερομηνία έκδοσης': '13/02/2026'},
  {'Φορέας': 'ΔΗΜΟΣ ΣΟΥΦΛΙΟΥ'},
  {'Οργανωτικές Μονάδες': ['ΔΙΕΥΘΥΝΣΗ ΟΙΚΟΝΟΜΙΚΩΝ ΥΠΗΡΕΣΙΩΝ']},
  {'Υπογράφοντες': ['Αντιδήμαρχος - ΤΣΙΑΜΙΤΑΣ ΘΕΟΔΩΡΟΣ']},
  {'Οικονομικό Έτος': '2026'},
  {'Κατηγορία Προϋπολογισμού': 'Πρόγραμμα Δημοσίων Επενδύσεων'},
  {'Αρ. Καταχώρησης': None},
  {'Τμηματική Ανάληψη': 'ΌΧΙ'},
  {'Ανακλητική Απόφαση': 'ΌΧΙ'},
  {'Συνολικό ποσό': {'Ποσό': '8.433,13', 'Νόμισμα': 'Ευρώ'}},
  {'Ποσό και ΚΑΕ/ΑΛΕ': []},
  {'Σχετ. αρχική τμηματική': None},
  {'Δείτε επίσης και ..': []},
  None],
 'status': 'PUBLISHED',
 'documentType': 'ΠΡΑΞΗ',
 'versionId': '1236ca47-c8a4-42e0-8b05-17b407b27b06',
 'attachments': [],
 'organizationId': '6284',
 'references': [],
 'backReferences': [],
 'diavgeiaVersion': 'ΔΙΑΥΓΕΙΑ ΙΙ'}

In [206]:
from validate_diavgeia_amounts import validate_amount_for_ada, load_raw_rows, load_pdf_text_lookup

raw_df = load_raw_rows()
pdf_lookup = load_pdf_text_lookup()

r = validate_amount_for_ada(
    "ΨΣΣΞΩ9Ζ-5Η5",
    field="direct_value",
    raw_df=raw_df,
    pdf_text_by_ada=pdf_lookup,
)

r
r.exact_match_found
r.exact_matches
r.same_digits_candidates

[]

In [207]:
print(r)

AmountValidationResult(ada='ΨΣΣΞΩ9Ζ-5Η5', field='direct_value', raw_value='875.524,00', raw_value_candidates=['875.524,00'], pdf_available=True, exact_match_found=False, exact_matches=[], same_digits_candidates=[])

In [209]:
m = re.match(r"\b(.*?),00$", r.raw_value or "")
raw_digits = (m.group(1) if m else (r.raw_value or "")).replace(".", "").replace(",", "")

pdf_digits = [
    x.replace(".", "").replace(",", "").replace(" ", "")
    for x in re.findall(r"(\d[\d., ]*?)(?:€|ευρώ|Euros|Ευρώ|ευρω|Ευρω|euros)", pdf_lookup["ΨΣΣΞΩ9Ζ-5Η5"])
]

raw_digits in pdf_digits

True

In [210]:
pdfs = pd.read_csv("../data/pdf_pages_dataset.csv")

In [211]:
pdfs.head(1)

,ada,file_name,page_count,text,text_length,parse_error
0,456546ΨΧΕΔ-ΧΕ2,456546ΨΧΕΔ-ΧΕ2.pdf,1,ΑΔΑ: 456546ΨΧΕΔ-ΧΕ2\nΑΝΑΡΣΗΣΕΑ ΢ΣΟ ΔΙΑΔΙΚΣΤΟ\n...,1028,NaN

In [212]:
df = pd.read_csv("../data/2026_diavgeia.csv")

In [225]:
df[df.ada=="998ΩΩ93-8ΕΔ"]

,ada,protocolNumber,issueDate,submissionTimestamp,publishTimestamp,status,nonRevokable,documentUrl,subject,documentType,versionComment,decisionType,thematicCategories,organization,cooperatingOrganizations,unitIds,org,org_type,org_name_clean,spending_signers,spending_contractors_afm,spending_contractors_name,spending_contractors_value,spending_contractors_currency,spending_contractors_count,spending_contractors_details,spending_enrichment_status,spending_enrichment_error,commitment_signers,commitment_fiscal_year,commitment_budget_category,commitment_counterparty,commitment_amount_with_vat,commitment_remaining_available_credit,commitment_kae_ale_number,commitment_remaining_kae_ale,commitment_lines_count,commitment_lines_details,commitment_enrichment_status,commitment_enrichment_error,direct_signers,direct_afm,direct_name,direct_value,direct_related_commitment,direct_see_also,direct_people_count,direct_people_details,direct_enrichment_status,direct_enrichment_error,payment_signers,payment_beneficiary_afm,payment_beneficiary_name,payment_value,payment_related_commitment_or_spending,payment_see_also,payment_beneficiaries_count,payment_beneficiaries_details,payment_enrichment_status,payment_enrichment_error,subject_has_keyword,subject_match,pdf_match,pdf_available_for_filter,is_relevant,matched_keywords_subject,matched_keywords_pdf
141,998ΩΩ93-8ΕΔ,3712/2026,02/02/2026 02:00:00,02/02/2026 09:58:58,02/02/2026 09:58:58,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/998ΩΩ93-8ΕΔ,ΔΗΜΙΟΥΡΓΙΑ ΠΕΡΙΜΕΤΡΙΚΩΝ ΑΝΤΙΠΥΡΙΚΩΝ ΖΩΝΩΝ ΜΕΣΟ...,ΠΡΑΞΗ,NaN,ΑΝΑΛΗΨΗ ΥΠΟΧΡΕΩΣΗΣ,['ΟΙΚΟΝΟΜΙΚΕΣ ΚΑΙ ΕΜΠΟΡΙΚΕΣ ΣΥΝΑΛΛΑΓΕΣ'],"{'uid': '6075', 'label': 'ΔΗΜΟΣ ΔΙΟΝΥΣΟΥ', 'ac...",NaN,NaN,ΔΗΜΟΣ ΔΙΟΝΥΣΟΥ,ΔΗΜΟΣ,ΔΙΟΝΥΣΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ΜΑΪΧΟΣΟΓΛΟΥ ΑΙΚΑΤΕΡΙΝΗ,2026.0,Τακτικός Προϋπολογισμός,NaN,"239.665,44",NaN,NaN,NaN,0.0,[],ok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,True,"['αντιπυρ', 'δασικων πυρκαγιων']","['πυροπροστ', 'αντιπυρ', 'δασικων πυρκαγιων', ..."

In [ ]:
for i, item in df_filtered[16:50].iterrows():
    clean_value=''
    pdf_digits=[]
    text = pdfs[pdfs.ada == item['ada']]['text'].item()
    value = [
    item[x][0] if isinstance(item[x], list) 
    else (item[x].replace("['", "").replace("']", "") if isinstance(item[x], str) else item[x])
    for x in AMOUNT_FIELDS 
    if pd.notna(item[x]) and str(item[x]) != "[]"
]
    try:
        clean_value = re.match(r"\b(.*?,\d\d$)", value[0] or "").group(1).replace(".", "").replace(",", "")
        pdf_digits = [
        x.replace(".", "").replace(",", "").replace(" ", "")
        for x in re.findall(r"(\d[\d., ]*?)(?:€|ευρώ|Euros|Ευρώ|ευρω|Ευρω|euros|\)|\s)", pdf_lookup[item['ada']])
    ]
    except Exception as e:
        print(f"**ada: {item['ada']}: e: {e}\
            \nspending_contractors_value: {item['spending_contractors_value']}\
            \ncommitment_amount_with_vat: {item['commitment_amount_with_vat']}\
            \ndirect_value: {item['direct_value']}\
            \npayment_value: {item['payment_value']}"
            )
        print("==========================")
        continue
    if clean_value not in pdf_digits:
        print(item['ada'])
        # if item['ada']=="998ΩΩ93-8ΕΔ":
        print(i)
        print(f"spending_contractors_value: {item['spending_contractors_value']}\
                \ncommitment_amount_with_vat: {item['commitment_amount_with_vat']}\
                \ndirect_value: {item['direct_value']}\
                \npayment_value: {item['payment_value']}")
        print(f"clean value: {clean_value}")
        print(f"pdf digits = {[x for x in pdf_digits if x.startswith(clean_value[:1])]}")
        print("************************")
        print(clean_value in pdf_digits)
        print("==========================")

# print(text)

9Ψ3ΚΩ15-2ΛΥ
92
spending_contractors_value: nan
commitment_amount_with_vat: 50.350,20
direct_value: nan
payment_value: nan
clean value: 5035020
pdf digits = ['5', '5']
************************
False
==========================
ΡΖΕΘΩΞ4-Ο0Σ
150
spending_contractors_value: nan
commitment_amount_with_vat: 6.352.998,91
direct_value: nan
payment_value: nan
clean value: 635299891
pdf digits = ['654728', '654728', '62', '60802', '60802', '6', '6', '6900', '693', '6900', '691', '630', '6060415001', '6913', '67', '67', '68', '69', '61211', '61211', '61073', '61073', '6', '631', '6060545001', '615', '6', '60', '60', '6915', '61', '61', '67', '62', '62', '63', '63', '642025', '649', '686', '64', '64', '6464', '65', '65', '66', '66', '67', '67', '658', '68', '68', '65', '69', '69', '64', '634', '6', '6061625001', '6061625002', '652', '6906', '633', '62025', '690358', '690358', '663', '676', '62025', '619', '62025', '62024', '616', '6193', '641', '62025', '6182', '6', '62025', '662025', '6469', '6435', '600017', '600008', '636', '662', '66000', '62000', '63100', '63100', '6', '61101', '61101', '690', '689', '625', '6825', '682', '60836', '672025', '6337', '6286', '6979', '6448', '647', '672025', '6', '644', '66', '60000', '671139', '671139', '6', '6066435001', '664', '669', '666', '667', '668', '684', '67084', '671', '6471315002', '692415', '692415', '6', '64143837', '6373125002', '64143837', '6173215001', '6473225003', '6473235005', '6473235006', '682024', '6173265001', '6173265002', '6173265003', '640', '62021', '62023', '6473335001', '6373365007', '6373365008', '6', '6373365010', '6473415001', '6473415003', '6473415004', '6000', '6000', '6000', '6000', '6000', '6000', '6000', '6000', '60', '61', '6111', '6117', '62', '62', '61', '6117', '62', '64', '610', '66', '602', '6200', '6939', '6442', '6', '62025', '63', '61', '60', '67', '6061625003', '6917', '6061315001', '6075', '6064745002', '697', '6371355001', '6', '628', '606', '622', '6825', '658', '617', '607', '623', '697', '6825', '653', '624', '6825', '678', '643', '681', '6473235007', '626944', '626944']
************************
False
==========================
**ada: ΨΕΟΒΩΨΑ-ΣΩΩ: e: 'NoneType' object has no attribute 'group'
spending_contractors_value: nan
commitment_amount_with_vat: -130,00
direct_value: nan
payment_value: nan
==========================
ΨΕΟΒΩΨΑ-ΣΩΩ
153
spending_contractors_value: nan
commitment_amount_with_vat: -130,00
direct_value: nan
payment_value: nan
clean value:
pdf digits = []
************************
False
==========================
**ada: ΨΒΛΞΩΨΑ-ΜΤΤ: e: 'NoneType' object has no attribute 'group'
spending_contractors_value: nan
commitment_amount_with_vat: -100,00
direct_value: nan
payment_value: nan
==========================
ΨΒΛΞΩΨΑ-ΜΤΤ
154
spending_contractors_value: nan
commitment_amount_with_vat: -100,00
direct_value: nan
payment_value: nan
clean value:
pdf digits = []
************************
False
==========================
**ada: ΨΘ2ΒΩΨΑ-0ΒΔ: e: 'NoneType' object has no attribute 'group'
spending_contractors_value: nan
commitment_amount_with_vat: -100,00
direct_value: nan
payment_value: nan
==========================
ΨΘ2ΒΩΨΑ-0ΒΔ
160
spending_contractors_value: nan
commitment_amount_with_vat: -100,00
direct_value: nan
payment_value: nan
clean value:
pdf digits = []
************************
False
==========================
**ada: ΨΡΙ6ΩΚ4-Ι7Ζ: e: 'NoneType' object has no attribute 'group'
spending_contractors_value: nan
commitment_amount_with_vat: -60.000,00
direct_value: nan
payment_value: nan
==========================
ΨΡΙ6ΩΚ4-Ι7Ζ
173
spending_contractors_value: nan
commitment_amount_with_vat: -60.000,00
direct_value: nan
payment_value: nan
clean value:
pdf digits = []
************************
False
==========================
6ΙΤΝΩ96-ΠΙΓ
200
spending_contractors_value: nan
commitment_amount_with_vat: 32.397.672,93
direct_value: nan
payment_value: nan
clean value: 3239767293

In [254]:
"2020"[:1]

'2'

In [216]:
df[df['spending_contractors_value']=="[]"]

Empty DataFrame
Columns: [ada, protocolNumber, issueDate, submissionTimestamp, publishTimestamp, status, nonRevokable, documentUrl, subject, documentType, versionComment, decisionType, thematicCategories, organization, cooperatingOrganizations, unitIds, org, org_type, org_name_clean, spending_signers, spending_contractors_afm, spending_contractors_name, spending_contractors_value, spending_contractors_currency, spending_contractors_count, spending_contractors_details, spending_enrichment_status, spending_enrichment_error, commitment_signers, commitment_fiscal_year, commitment_budget_category, commitment_counterparty, commitment_amount_with_vat, commitment_remaining_available_credit, commitment_kae_ale_number, commitment_remaining_kae_ale, commitment_lines_count, commitment_lines_details, commitment_enrichment_status, commitment_enrichment_error, direct_signers, direct_afm, direct_name, direct_value, direct_related_commitment, direct_see_also, direct_people_count, direct_people_details, direct_enrichment_status, direct_enrichment_error, payment_signers, payment_beneficiary_afm, payment_beneficiary_name, payment_value, payment_related_commitment_or_spending, payment_see_also, payment_beneficiaries_count, payment_beneficiaries_details, payment_enrichment_status, payment_enrichment_error, subject_has_keyword, subject_match, pdf_match, pdf_available_for_filter, is_relevant, matched_keywords_subject, matched_keywords_pdf]
Index: []

In [217]:
AMOUNT_FIELDS = [
    "spending_contractors_value",
    "commitment_amount_with_vat",
    "direct_value",
    "payment_value",
]
df_filtered = df.dropna(subset=AMOUNT_FIELDS, how='all')

In [218]:
df_filtered.shape

(5384, 67)

In [129]:
re.match(r"\b(.*?),00$", r.raw_value).group(1).replace('.',"").replace(",","")

'875524'

In [ ]:
re.match(r"(.*?),00$", r.raw_value).group(1).replace('.',"").replace(",","") in [x.replace('.',"").replace(",","") for x in re.findall(r"(\d.*?)(?:€|ευρώ|Euros|Ευρώ|ευρω|Ευρω|euros)", pdf_lookup["ΨΣΣΞΩ9Ζ-5Η5"])]

True

In [111]:
[x.replace('.',"").replace(",","") for x in re.findall(r"(\d.*?)(?:€|ευρώ)", pdf_lookup["ΨΣΣΞΩ9Ζ-5Η5"])]

['75000',
 '8000',
 '30000',
 '35000',
 '6000',
 '95000',
 '98000',
 '430280',
 '430280',
 '875524']

In [94]:
print(pdf_lookup["ΨΣΣΞΩ9Ζ-5Η5"])

22AWRD011221111 2022-09-09
ΕΛΛΗΝΙΚΗ ΔΗΜΟΚΡΑΤΙΑ
ΝΟΜΟΣ ΦΩΚΙΔΑΣ
ΔΗΜΟΣ ΔΩΡΙΔΟΣ
Αριθ.Πρωτ.8095
ΘΕΜΑ: Ανάθεση της εργασίας «Συντήρηση και επισκευή των µε αρ. κυκλ. ΜΕ-73917 µάρκας FOREDIL MACHINE
AMBIENTE ΠΟΛΥΜΗΧΑΝΗΜΑ
Η ΕΠΙΤΡΟΠΗ ΣΥΝΤΗΡΗΣΗΣ ΚΑΙ ΕΠΙΣΚΕΥΗΣ ΟΧΗΜΑΤΩΝ-ΜΗΧΑΝΗΜΑΤΩΝ ΔΗΜΟΥ
ΔΩΡΙΔΟΣ ΠΟΥ ΣΥΓΚΡΟΤΗΘΗΚΕ ΜΕ ΤΗΝ 232/2022
Έχοντας λάβει υπόψη:
1.Το αρ. 103 παρ. 1γ΄ και τον 209 ΔΚΚ (Ν. 3463/2006).
2. Το άρ. 72 παρ. 1 δ΄ του Ν. 3852/2010 όπως όπως τροποποιήθηκε από την παρ.1 του
άρθρου 3 του Ν.4623/2019.
3. Τον Ν.4555/2018 (Α' 133/19-7-2018). [Πρόγραμμα «ΚΛΕΙΣΘΕΝΗΣ Ι»].
4.Το Ν. 4412/2016 (ΦΕΚ Α΄147/8-8-2016) Δημόσιες Συμβάσεις Έργων, Προμηθειών και
Υπηρεσιών (προσαρμογή στις Οδηγίες 2014/24/ ΕΕ και 2014/25/ΕΕ) όπως τροποποιήθηκε
από το ν. 4605/19 (ΦΕΚ Α’ 52/1-4-2019).
5. Τη με αριθ. ΥΑ 3373/390/20-03-1975 (ΦΕΚ 349/τ. Β΄/20-03-1975) απόφαση του
Υπουργείου Προεδρίας της Κυβερνήσεως «περί καθορισμού διαδικασίας επισκευής,
συντηρήσεως, αγοράς ανταλλακτικών και προμήθειας καυσίμων και λιπαντικών κ.λπ. των
αυτοκινήτων οχημάτων του Δημοσίου, των Οργανισμών Τοπικής Αυτοδιοικήσεως και των
εν γένει Νομικών Προσώπων Δημοσίου Δικαίου.
6.Τη με αριθμ. 232/2022 Απόφαση Δημάρχου Δωρίδος για την συγκρότηση της Επιτροπής
Συντήρησης και Επισκευής Οχημάτων- Μηχανημάτων του Δήμου Δωρίδος για το έτος
2022.ΑΔΑ :(Ψ40ΝΩ9Ζ-Φ98)
7.Τη με αριθμ. 17/2022 Απόφαση Δημάρχου Δωρίδος για τον ορισμό Αναπληρωτών
Διευθυντών & προϊσταμένων του Δήμου Δωρίδος .ΑΔΑ:(Ψ9ΓΤΩ9Ζ-ΙΓΚ)
8..Τις διατάξεις της παρ. 13 του άρθρου 20 του Ν. 3731/2008 όπως αντικαταστάθηκε με το
Ν4270
αντικαταστάθηκε από την παρ. 1 του άρθρου 203 του Ν. 4555/2018 ( Α΄133).)
9. Τις διατάξεις του άρθρου 83 του ν. 2362/1995 (ΦΕΚ 247 Α)
10.Την υπ' αριθ. απόφαση Υπουργού Οικον. 2/45564/0026/01 (ΦΕΚ 1066 τ. Β΄)
11. Τον Ο.Ε.Υ. Δ. Δωρίδος Ν. Φωκίδας (2552/Β΄16-06-2021)
12. Η με άριθμ. 105/2016 πράξη του 7ου Τμήματος του ελεγκτικού Συνεδρίου σύμφωνα με
την οποία η επισκευή έκτακτης βλάβης οχήματος, συνιστά επείγουσα ανάγκη, η δε
άμεση αποκατάσταση της βλάβης είναι αναγκαία προκειμένου να μη διαταραχθεί η ομαλή
λειτουργία των υπηρεσιών.
13.Τη με άριθμ. 109/2013 πράξης του 7ου Τμήματος του ελεγκτικού Συνεδρίου όπου
ορίζεται ότι μόνη επιτροπή για την ανάθεση προμήθειας ανταλλακτικών είναι η επιτροπή
συντήρησης και επισκευής οχημάτων του Δήμου.
14.Tις διατάξεις του άρθρου 72 παρ. 1δ΄του Ν. 3852/2010 όπως αντικαταστάθηκε από το
παρ.1 του άρθρου 3 του Ν.4623/2019 σύμφωνα με τις οποίες «η οικονομική επιτροπή
είναι συλλογικό όργανο, αρμόδιο για τον έλεγχο και την παρακολούθηση της
οικονομικής λειτουργίας του δήμου».
15.Το γεγονός ότι δεν υπάρχει εξασφαλισμένη πίστωση για την αναφερόμενη δαπάνη και
θα εγγραφεί στον προϋπολογισμό οικονομικού έτους 2022 μετά από αναμόρφωση
αρθ.158 & 160 του Ν. 3463/2006, εγκύκλιος 487/2020 .
Κ.Α. 30-6263.002 Συντήρηση και επισκευή λοιπών μηχανημάτων έργου (GRADER,
εκσκαφέων κλπ μηχανημάτων έργων) - ΕΚΤΑΚΤΑ
16.Το με αριθμό ΚΗΜΔΗΣ 22REQ011220888 2022-09-09 πρωτογενές αίτημα.
17. Εντολή επιθεώρησης και επισκευής οχημάτων με αριθμ. πρωτ.4684/01/06-2022&
8093/17-08-25022 που εκδόθηκε από το τμήμα κίνησης και συντήρησης οχημάτων και
εξοπλισμού
18. Λόγω έλλειψης ιδίου Συνεργείου στο Δήμο Δωρίδος
19. Τις προσφορές των αφοί Π. Διδάχου Ο.Ε. με αριθμ. πρωτ. 8094/17-08-2022προς το
Δήμο Δωρίδος.
20. Τα σχετικά έγγραφα του γραφείου κίνησης για τη συντήρηση και επισκευή των
κατωτέρω οχημάτων μηχανημάτων.
21. Με βάση τα παραπάνω και επειδή οι εξαιρετικά επείγουσες ανάγκες οφείλονται σε
γεγονότα απρόβλεπτα δεν είναι δυνατή η τήρηση των προθεσμιών που προβλέπονται

22AWRD011221111 2022-09-09
για τις ανοικτές, κλειστές ή με διαπραγμάτευση διαδικασίες με δημοσίευση προκήρυξης
διαγωνισμού λόγο του απρόβλεπτου χαρακτήρα των βλαβών.
22.Οι περιστάσεις της κατεπείγουσας ανάγκης σε καμία περίπτωση δεν απορρέουν από
ευθύνη του Δήμου.
23. Η προμήθεια των αναγκαίων ανταλλακτικών και οι επισκευαστικές εργασίες
είναι κατεπείγουσα ανάγκη αφού σχετίζεται με λόγους δημόσιας υγείας και
την ασφάλεια του προσωπικού του Δήμου μας και είναι απαραίτητη
προκειμένου να αυξηθεί η επιχειρησιακή τους δυνατότητα και να βελτιωθεί η
λειτουργικότητά τους ,καθόσον πρόκειται για όχημα ME -73917 μάρκας
FOREDIL MACHINE AMBIENTE ΠΟΛΥΜΗΧΑΝΗΜΑ εκσκαφέας φορτωτής που
χρησιμοποιείτε από την Διεύθυνση Τεχνικών Υπηρεσιών του Δήμου Δωρίδος.
Χρησιμοποιείτε καθημερινά στον καθαρισμό αγροτικών και δασικών δρόμων
,την δημιουργία αντιπυρικών ζωνών, καθαρισμούς δρόμων από χιόνια ,Βλάβες
στο δίκτυο ύδρευσης.
ΑΠΟΦΑΣΙΖΟΥΜΕ
1) Αναθέτουμε απευθείας την εργασία <<Συντήρηση και επισκευή του οχήματος>> με αρ.
κυκλ. ΜΕ-73917 μάρκας FOREDIL MACHINE AMBIENTE ΠΟΛΥΜΗΧΑΝΗΜΑ στον
ΔΙΔΑΧΟΥ Π. ΑΦΟΙ Ο.Ε. , ΕΠΙΣΚΕΥΑΣΤΙΚΗ ΚΑΤΑΣΚΕΥΑΣΤΙΚΗ ΕΜΠΟΡΙΚΗ
ΕΤΑΙΡΕΙΑ ΑΝΤΑΛΑΚΤΙΚΩΝ, Δ/νση ΠΑΤΡΩΝ ΠΥΡΓΟΥ 6 ΠΑΤΡΑ , ΑΦΜ
081197257, Δ.Ο.Υ. ΠΑΤΡΩΝ. τηλ. 2610528445
Η εργασία και τα ανταλλακτικά περιγράφονται ως τα εξής:
α/α ΕΙΔΟΣ ΕΡΓΑΣΙΑΣ ΕΝΔΕΙΚΤΙΚΟ ΕΝΔΕΙΚΤΙΚΟ ΕΝΔΕΙΚΤΙΚΟ
ΚΟΣΤΟΛΟΓΙΟ ΚΟΣΤΟΛΟΓΙΟ ΚΟΣΤΟΛΟΓΙΟ
ΑΝΤΑΛ/ΚΩΝ- ΕΡΓΑΣΙΩΝ ΜΕ ΑΝΤΑΛ/ΚΩΝ
ΕΡΓΑΣΙΩΝ ΧΩΡΙΣ ΦΠΑ 24% ΜΕ ΦΠΑ 24%
ΦΠΑ
1. ΜΕ- ΠΡΟΜΗΘΕΙΑ ΑΝΤΑΛΑΚΤΙΚΩΝ
73917 ΜΠΑΤΑΡΙΑ 83,37
ΕΚΚΕΝΤΡΟ ΡΟΤΟΡΑ 221,37
ΕΚΚΕΝΤΡΟ ΜΕΤΑΦΟΡΙΚΗ 28,80
ΤΑΠΑ 9,00
ΣΕΤ ΕΠΙΣΚΕΥΗΣ ΑΝΤΛΙΑΣ 82,08
ΤΣΙΜΟΥΧΑ 9,90
ΟΡΙΝΓΚ 2,00
ΟΡΙΝΓΚ 3,80
ΟΡΙΝΓΚ 3,10
ΟΡΙΝΓΚ 3,85
ΦΑΝΑΡΙ – ΦΛΑΣ ΕΜΠΡΟΣΘΙΟ 48,50
ΛΑΜΠΑ 12V 21W 0,80
ΛΑΜΠΑ 12V 4W 0,40
ΑΣΦΑΛΕΙΑ ΔΙΧΑΛΩΤΗ 0,60
ΠΟΛΟΣ ΜΠΑΤΑΡΙΑΣ 4,80
ΑΣΦΑΛΕΙΟΘΗΚΗ ΑΔΙΑΒΡΟΧΗ 10,00
ΑΣΦΑΛΕΙΑ ΜΑΧΑΙΡΩΤΗ 1,10
ΠΡΟΒΟΛΕΑΣ ΕΡΓΑΣΙΑΣ 23,50
ΚΟΡΝΑ 10,00
ΡΟΔΕΛΛΑ ΦΑΡΔΙΑ Μ8 0,15
ΡΕΛΕ 12V 40A 5,00
ΚΟΡΝΑ ΟΠΙΣΘΕΝ 14,50
ΒΙΔΑ 8Χ50 0,30
ΡΟΔΕΛΑ Μ10 0,15
ΥΑΛΟΚΑΘΑΡΙΣΤΗΡΕΣ 8,97
ΦΑΝΟΣ ΟΠΙΣΘΙΟΣ 35,10
ΦΑΡΟΣ 46,80
ΚΑΛΩΔΙΟ ΕΥΚΑΜΠΤΟ 0,95
ΜΑΚΑΡΟΝΙ ΣΩΛΗΝΑ Φ 7 1,58
ΦΙΛΤΡΟ ΛΑΔΙΟΥ 15,00
ΦΙΛΤΡΟ ΠΕΤΡΕΛΑΙΟΥ 16,50

22AWRD011221111 2022-09-09
ΤΣΙΜΟΥΧΑ ΜΟΥΑΓΕ 98,20
ΣΥΡΜΑ 2,5 ΜΜ 4,82
ΦΩΛΙΑ 0,98
ΣΦΟΧΤΗΡΑΣ ΣΥΡΜΑΤΟΣ 1,00
ΣΥΡΜΑΤΟΣΧΟΙΝΟ 3,45
ΚΑΛΥΜΑ ΝΤΙΖΑΣ 5,63
ΕΞΑΡΤΗΜΑΤΑ ΝΤΙΖΑΣ 3,50
ΑΞΟΝΑΚΙ
ΚΑΛΥΜΑ ΝΤΙΖΑΣ 6 mm ΜΕ 6,87
ΤΕΦΛΟΝ 1,32
ΣΥΡΜΑΤΟΣΧΟΙΝΟ 2mm 6,00
ΘΗΛΙΕΣ 1,92
ΚΥΑΘΙΟ ¼ 8,07
ΣΩΛΗΝΑΣ ¼ 2,90
ΡΑΚΟΡ ΚΑΜΠΥΛΗ 2,50
ΡΑΚΟΡ ΘΗΛΥΚΟ 10,04
ΣΩΛΗΝΑΣ 40,17
ΦΙΛΤΡΟ ΛΑΔΙΟΥ 17,50
ΦΙΛΤΡΟ ΑΕΡΟΣ 39,20
ΦΙΛΤΡΟ ΛΑΔΙΟΥ 28,00
ΦΙΛΤΡΟ ΥΔΡΑΥΛΙΚΟΥ 10,00
ΒΑΛΒΟΛΙΝΗ TG80W/10W30 89,20
ΡΟΥΛΕΜΑΝ ΤΡΟΧΟΥ 9,00
ΡΑΚΟΡ ΚΑΜΠΥΛΗ 20,22
ΣΩΛΗΝΑΣ 3,85
ΚΥΑΘΙΟ ΑΚΑΘΑΡΙΣΤΟ 1,10
ΣΦΙΧΤΗΡΑΣ 9,00
ΣΩΛΗΝΑΣ ΚΑΥΣΙΜΟΥ 7,50mm 6,00
ΣΩΛΗΝΑΣ ΝΕΡΟΥ 16mm 1,80
ΣΦΙΧΤΗΡΑΣ 12,50
ΙΜΑΝΤΑΣ 13Χ1375 4,94
ΛΑΔΙ 15W40 3,00
ΛΑΔΙ ΥΔΡΑΥΛΙΚΟΥ 3,98
ΑΝΤΙΨΥΚΤΙΚΟ 299,95
ΣΕΤ ΜΑΡΚΟΥΤΣΙΑ 2,00
ΚΑΤΑΣΤΡΟΦΕΑ 3,50
ΣΤΗΡΙΓΜΑ ΣΙΔΗΡΟΣΩΛΗΝΩΝ 6,85
ΚΥΑΘΙΟ 5/8 8,76
ΡΑΚΟΡ ΘΗΛΥΚΟ 4,03
ΡΑΚΟΡ ΚΑΜΠΥΛΗ 25,79
ΤΣΙΜΟΥΧΑ 18,10
ΜΑΡΚΟΥΤΣΙ ΥΔΡΑΥΛΙΚΟΥ
ΚΑΠΑΚΙ ΕΞΑΤΜΙΣΗΣ Φ50 95,00
ΚΑΘΡΕΠΤΗΣ ΜΠΡΑΤΣΑ 0,35
ΜΕΤΑΧΕΙΡΙΣΜΕΝΑ 0,18 3590,68Χ24%=
ΒΙΔΑ ΕΞΑΓ.8,80 ΓΑΛΒ. 8Χ40 0,38
ΡΟΔΕΛΑ DIN M8 0,12
ΒΙΔΑ ΕΞΑΓ. 8,8 ΓΑΛΒ. 10Χ80 0,30
ΡΟΔΕΛΛΑ DIN M10 0,12
ΠΑΞΙΜΑΔΙ ΑΣΦΑΛΕΙΑΣ Μ10 0,20
ΡΟΔΕΛΑ DIN M6 0,35
ΒΙΔΑ ΕΞΑΓ. 8Χ20 180,00
ΠΑΞΙΜΑΔΙ ΑΣΦΑΛΕΙΑΣ Μ8 32,80
ΑΝΤΛΙΑ ΦΡΕΝΟΥ 25,79
ΔΕΙΚΤΗΣ ΛΑΔΙΟΥ 10,11
ΜΑΡΚΟΥΤΣΙ ΥΔΡΑΥΛΙΚΟΥ 25,79
ΤΣΙΜΟΥΧΑ 28Χ40Χ7 6,00
ΜΑΡΚΟΥΤΣΙ ΥΔΡΑΥΛΙΚΟΥ 20,00
ΤΣΙΜΟΥΧΑ ΑΞΟΝΑ
ΣΣΩΛΗΝΑΣ ΙΝΟΧ ΣΥΝΟΛΟ
:4.452,44

22AWRD011221111 2022-09-09
ME- ΕΡΓΑΣΙΑ ΤΟΠΟΘΕΤΗΣΗΣ
73917 ΑΝΤΑΛΑΚΤΙΚΩΝ
 ΜΕΤΑΦΟΡΑ
ΜΗΧΑΝΗΜΑΤΟΣ ΑΠΟ
ΕΥΠΑΛΙΟ ΣΤΟ ΣΥΝΕΡΓΕΙΟ ΜΑΣ
& ΕΠΙΣΤΡΟΦΗ ΑΥΤΟΥ. 750,00€
 ΠΕΤΡΕΛΑΙΟ. 80,00€
 ΕΡΓΑΣΤΗΡΙΟ
ΑΝΤΛΙΩΝ: ΕΞΑΓΩΓΗ-
ΤΟΠΟΘΕΤΗΣΗ-ΕΠΙΣΚΕΥΗ &
ΡΥΘΜΙΣΗ ΑΝΤΛΙΑΣ 300,00€
ΠΕΤΡΕΛΑΙΟΥ.
 ΑΛΛΑΓΗ :
ΕΜΠΡΟΣΘΙΩΝ ΦΑΝΑΡΙΩΝ –
ΡΕΛΕ ΦΩΤΩΝ-ΡΕΛΕ ΓΙΑ ΤΗΝ
ΚΙΝΗΣΗ ΤΟΥ
ΜΗΧΑΝΗΜΑΤΟΣ-ΜΠΑΤΑΡΙΕΣ-
ΠΡΟΒΟΛΕΩΝ ΕΡΓΑΣΙΑΣ
ΕΜΠΡΟΣ & ΠΙΣΩ ΣΤΟ ΑΝΩ
ΜΕΡΟΣ ΤΗΣ ΚΑΜΠΙΝΑΣ-
ΚΟΡΝΑΣ & ΒΟΜΒΗΤΗ
ΟΠΙΣΘΕΝ.
 ΤΟΠΟΘΕΤΗΣΗ :
ΑΣΦΑΛΕΙΟΘΗΚΗΣ & 350,00€
ΦΑΡΩΝ.ΑΛΛΑΓΗ ΜΑΚΤΡΩΝ
ΥΑΛΟΚΑΘ/ΡΩΝ ΚΑΙ
ΠΟΛΩΝ ΜΠΑΤΑΡΙΑΣ.
 ΑΛΛΑΓΗ: ΛΑΔΙ
ΚΙΝΗΤΗΡΑ & ΦΙΛΤΡΑ: ΛΑΔΙΟΥ-
ΠΕΤΡΕΛΑΙΟΥ-ΑΕΡΟΣ- 60,00€
ΥΔΡΑΥΛΙΚΟΥ
ΚΑΘΑΡΙΣΜΟΣ ΠΡΟΦΙΛΤΡΟ

22AWRD011221111 2022-09-09
ΠΕΤΡΕΛΑΙΟΥ.ΑΛΛΑΓΗ
ΑΝΤΙΨΥΚΤΙΚΟΥ ΥΓΡΟΥ.
 ΕΞΑΓΩΓΗ ΤΕΣΣΑΡΩΝ
ΤΡΟΧΩΝ, ΕΞΑΓΩΓΗ ΤΩΝ
ΜΕΙΩΤΗΡΩΝ, ΑΠΟΣΥΝ/ΣΗ
ΜΕΙΩΤΗΡΩΝ, ΑΛΛΑΓΗ ΣΕΤ
ΣΤΕΓΑΝΟΠΟΙΗΣΗΣ -ΤΣΙΜΟΥΧΕΣ
ΣΥΝΑΡ/ΣΗ ΤΩΝ
ΜΕΙΩΤΗΡΩΝ & ΕΠΑΝΑΤ/ΣΗ
ΑΥΤΩΝ. ΕΛΕΓΧΟ ΤΩΝ
ΡΟΥΛΕΜΑΝ,ΑΛΛΑΓΗ
ΡΟΥΛΕΜΑΝ
ΕΞΩΤΕΡΙΚΟ ΑΡΙΣΤΕΡΟΥ
ΕΜΠΡΟΣΘΙΟΥ ΤΡΟΧΟΥ & ΣΤΟΝ
ΟΠΙΣΘΙΟ ΔΕΞΙΟ,
ΕΛΕΓΧΟ ΤΩΝ ΔΙΣΚΩΝ ΤΩΝ 950,00€
ΦΡΕΝΩΝ, ΣΥΝΑΡ/ΣΗ &
ΕΠΑΝΑΤ/ΣΗ ΤΩΝ ΤΡΟΧΩΝ
ΑΛΛΑΓΗ ΒΑΛΒΟΛΙΝΕΣ ΣΤΟΥΣ
ΜΕΙΩΤΗΡΕΣ ΓΕΝΙΚΟ
ΓΡΑΣΣΑΡΙΣΜΑ
ΜΗΧΑΝΗΜΑΤΟΣ
 ΤΟΠΟΘΕΤΗΣΗ
ΜΑΡΚΟΥΤΣΙΑ ΥΔΡΑΥΛΙΚΟΥ ΓΙΑ
ΤΗΝ ΚΙΝΗΣΗ ΚΑΤΑΣΤΡΟΦΕΑ
ΚΑΙ
ΣΤΗΡΙΞΗ ΑΥΤΩΝ. ΑΛΛΑΓΗ
ΙΜΑΝΤΑ ΔΥΝΑΜΟ,ΑΝΤΛΙΑΣ
ΝΕΡΟΥ. ΑΛΛΑΓΗ ΣΩΛΗΝΑ
ΝΕΡΟΥ ΑΠΟ ΑΝΤΛΙΑ ΝΕΡΟΥ ΣΕ
ΚΑΛΟΡΙΦΕΡ.ΑΛΛΑΓΗ ΣΩΛΗΝΑΣ
ΚΑΥΣΙΜΟΥ ΑΠΟ
ΡΕΖΕΡΒΟΥΑΡ ΣΕ ΑΝΤΛΙΑ ΚΑΙ
ΑΠΟ ΑΝΤΛΙΑ ΣΕ ΦΙΛΤΡΑ.
ΑΛΛΑΓΗ ΝΤΙΖΕΣ ΓΚΑΖΙΟΥ
ΚΑΙ ΝΤΙΖΕΣ
ΑΠΟΣΥΜΠΛΕΞΗΣ.ΑΛΛΑΓΗ
ΜΑΡΚΟΥΤΣΙ ΦΡΕΝΟΥ ΑΠΟ 3.470,00Χ24%=
ΑΝΤΛΙΑ ΣΕ
ΤΡΟΧΟ. ΑΛΛΑΓΗ ΜΑΡΚΟΥΤΣΙ
ΑΠΟ ΧΕΙΡΙΣΤΗΡΙΟ ΣΕ ΠΡΙΖΑ
ΥΔΡΑΥΛΙΚΟΥ.
ΑΛΛΑΓΗ ΔΕΙΚΤΗ ΕΝΔΕΙΞΗΣ
ΛΑΔΙΟΥ ΥΔΡΑΥΛΙΚΟΥ
ΚΑΤΑΣΚΕΥΗ ΒΑΣΕΙΣ ΚΑΙ
ΤΟΠΟΘΕΤΗΣΗ ΟΠΙΣΘΙΩΝ
ΦΑΝΑΡΙΩΝ.ΤΟΠΟΘΕΤΗΣΗ
ΚΑΘΡΕΠΤΩΝ.ΑΛΛΑΓΗ
ΒΙΔΕΣ ΣΤΗΝ ΠΟΔΙΑ ΤΟΥ
ΜΗΧΑΝΗΜΑΤΟΣ.ΑΛΛΑΓΗ
ΑΝΤΛΙΑΣ ΦΡΕΝΟΥ ΚΑΙ
ΕΞΑΕΡΩΣΗ ΦΡΕΝΩΝ. 980,00€
ΤΟΠΟΘΕΤΗΣΗ ΣΩΛΗΝΑ ΙΝΟΧ
ΣΤΗΝ ΕΞΑΤΜΙΣΗ.
ΕΞΑΓΩΓΗ ΠΛΑΣΤΙΚΑ
ΚΑΜΠΙΝΑΣ, ΕΠΙΣΚΕΥΗ ΣΥΝΟΛΟ:
ΟΥΡΑΝΟΥ & ΕΠΑΝΑΤ/ΣΗ 4.302,80€
ΠΛΑΣΤΙΚΩΝ ΜΕΤΑ ΤΩΝ
ΕΞΑΡΤΗΜΑΤΩΝ.

22AWRD011221111 2022-09-09
ΓΕΝΙΚΟ ΣΥΝΟΛΟ ΑΝΤΑΛΛΑΚΤΙΚΑ-ΕΡΓΑΣΙΕΣ ΓΕΝΙΚΟ ΣΥΝΟΛΟ: 4.302,80€
ΜΕ ΦΠΑ:
ΓΕΝΙΚΟ ΣΥΝΟΛΟ ΔΑΠΑΝΗΣ ΠΟΣΟ: 8.755,24€
Λιδωρίκι 17 Αυγούστου 2022
Η ΕΠΙΤΡΟΠΗ
Ο ΠΡΟΕΔΡΟΣ ΤΑ ΜΕΛΗ
1. ΚΩΝ/ΝΟΣ ΤΡΑΧΑΝΑΣ 1) ΓΑΛΑΝΗΣ ΠΑΝΑΓΙΩΤΗΣ
2)ΔΙΑΜΑΝΤΟΠΟΥΛΟΣ ΔΗΜΗΤΡΙΟΣ

In [64]:
df[df.ada==ada]

,ada,protocolNumber,issueDate,submissionTimestamp,publishTimestamp,status,nonRevokable,documentUrl,subject,documentType,...,payment_signers,payment_beneficiary_afm,payment_beneficiary_name,payment_value,payment_related_commitment_or_spending,payment_see_also,payment_beneficiaries_count,payment_beneficiaries_details,payment_enrichment_status,payment_enrichment_error
173,ΨΡΙ6ΩΚ4-Ι7Ζ,27511/2025,29/01/2026 02:00:00,29/01/2026 14:51:06,29/01/2026 14:51:06,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΨΡΙ6ΩΚ4-Ι7Ζ,ΑΝΑΤΡΟΠΗ ΨΗΦΙΣΜΕΝΗΣ ΠΡΟΤΑΣΗΣ,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
r.json()

{'ada': 'ΨΣΣΞΩ9Ζ-5Η5',
 'publishTimestamp': '09/09/2022 16:48:10',
 'submissionTimestamp': '09/09/2022 16:48:10',
 'documentUrl': 'https://diavgeia.gov.gr/doc/ΨΣΣΞΩ9Ζ-5Η5',
 'meta': [{'Είδος': 'ΑΝΑΘΕΣΗ ΕΡΓΩΝ / ΠΡΟΜΗΘΕΙΩΝ / ΥΠΗΡΕΣΙΩΝ / ΜΕΛΕΤΩΝ'},
  {'Θέμα': 'Ανάθεση της εργασίας «Συντήρηση και επισκευή των με αρ. κυκλ. ΜΕ-73917  μάρκας  FOREDIL MACHINE AMBIENTE ΠΟΛΥΜΗΧΑΝΗΜΑ'},
  {'Θεματικές κατηγορίες': ['ΟΙΚΟΝΟΜΙΚΕΣ ΚΑΙ ΕΜΠΟΡΙΚΕΣ ΣΥΝΑΛΛΑΓΕΣ']},
  {'Αρ. πρωτοκόλλου': '8095'},
  {'Ημερομηνία έκδοσης': '09/09/2022'},
  {'Φορέας': 'ΔΗΜΟΣ ΔΩΡΙΔΟΣ'},
  {'Οργανωτικές Μονάδες': ['ΤΜΗΜΑ ΠΡΟΜΗΘΕΙΩΝ ΚΑΙ ΑΠΟΘΗΚΩΝ']},
  {'Υπογράφοντες': ['ΚΑΠΕΝΤΖΩΝΗΣ ΓΕΩΡΓΙΟΣ']},
  {'ΑΦΜ / Επωνυμία προσώπου / προσώπων': [{'ΑΦΜ': '081197257',
     'Τύπος ΑΦΜ': 'Εθνικό',
     'Κράτος -μέλος της ΕΕ': None,
     'Επωνυμία': 'ΑΦΟΙ ΠΑΝΑΓ ΔΙΔΑΧΟΥ Ο Ε',
     'Οργανισμός χωρίς ΑΦΜ': None}]},
  {'Ποσό': {'Αξία': '875.524,00', 'Νόμισμα': 'Ευρώ'}},
  {'Κατηγορία': 'Υπηρεσίες'},
  {'CPV': None},
  {'Σχετ. Ανάληψη υποχρέωσης': None},
  {'Δείτε επίσης και ..': []},
  None],
 'status': 'PUBLISHED',
 'documentType': 'ΠΡΑΞΗ',
 'versionId': 'c4e9d568-c310-42e5-b2ba-fc1007cd6429',
 'attachments': [],
 'organizationId': '6085',
 'references': [],
 'backReferences': [],
 'diavgeiaVersion': 'ΔΙΑΥΓΕΙΑ ΙΙ'}

In [66]:
import importlib, fetch_diavgeia
importlib.reload(fetch_diavgeia)

stats = fetch_diavgeia.backfill_spending_approval_columns(
    overwrite_existing=False, 
    progress_every=10
)
stats

[spending] Backfilled CSV saved -> /Users/troboukis/Code/fire_protection_2026/data/2026_diavgeia.csv

{'rows_total': 22970,
 'rows_spending_approvals': 872,
 'rows_commitments': 1436,
 'rows_direct_assignments': 2064,
 'rows_payment_finalizations': 1893,
 'rows_newly_enriched': 0,
 'rows_commitments_newly_enriched': 0,
 'rows_direct_newly_enriched': 0,
 'rows_payment_newly_enriched': 0,
 'rows_ok_total': 872,
 'rows_commitments_ok_total': 1436,
 'rows_direct_ok_total': 2064,
 'rows_payment_ok_total': 1893,
 'rows_error_total': 0,
 'rows_commitments_error_total': 0,
 'rows_direct_error_total': 0,
 'rows_payment_error_total': 0}

In [53]:
df = pd.read_csv("../data/2026_diavgeia.csv")

In [68]:
df.tail(20)

,ada,protocolNumber,issueDate,submissionTimestamp,publishTimestamp,status,nonRevokable,documentUrl,subject,documentType,...,payment_beneficiary_afm,payment_beneficiary_name,payment_value,payment_related_commitment_or_spending,payment_see_also,payment_beneficiaries_count,payment_beneficiaries_details,payment_enrichment_status,payment_enrichment_error,subject_has_keyword
22950,Ψ4ΟΩΩ6Χ-ΖΦ5,294 - 11/2/2026,11/02/2026 02:00:00,20/02/2026 09:46:38,11/02/2026 09:21:20,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/Ψ4ΟΩΩ6Χ-ΖΦ5,Απόφαση Ανάληψης Υποχρέωσης Α-295 για :Ενίσχυσ...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
22951,Ψ28Μ4653Π8-5ΝΒ,62069,20/02/2026 02:00:00,20/02/2026 09:01:33,20/02/2026 09:01:33,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/Ψ28Μ4653Π8-5ΝΒ,Αναστολή υποχρέωσης αναδόχου από την εκτέλεση ...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
22952,ΨΡ8Σ4690ΒΓ-ΨΓ8,4637,19/02/2026 02:00:00,19/02/2026 19:59:04,19/02/2026 19:59:04,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΨΡ8Σ4690ΒΓ-ΨΓ8,ΕΓΚΡΙΣΗ Α ΤΡΟΠΟΠΟΙΗΣΗΣ ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΥ ΠΡΟΜΗΘΕ...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22953,Ρ45ΣΩΚ5-ΚΕΣ,1124 - 19/02/2026,19/02/2026 02:00:00,19/02/2026 15:04:58,19/02/2026 15:04:58,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/Ρ45ΣΩΚ5-ΚΕΣ,Απόφαση Ανάληψης Υποχρέωσης Α-155 για :Μελέτη ...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
22954,6ΥΨΜΩ1Ξ-ΘΧΠ,40827,19/02/2026 02:00:00,19/02/2026 13:17:29,19/02/2026 13:17:29,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/6ΥΨΜΩ1Ξ-ΘΧΠ,ΑΠΟΦΑΣΗ ΕΓΚΡΙΣΗΣ ΑΝΤΙΛΟΓΙΣΜΩΝ ΚΑΙ ΑΝΑΤΡΟΠΩΝ ΑΑ...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22955,6ΔΗΚ46ΜΓ3Ξ-9ΤΒ,1014/2026,19/02/2026 02:00:00,19/02/2026 13:02:27,19/02/2026 13:02:27,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/6ΔΗΚ46ΜΓ3Ξ-9ΤΒ,Κατάρτιση προϋπολογισμού Δήμου Ληξουρίου οικον...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22956,9ΠΚ4ΩΕ6-ΕΛΑ,5144,19/02/2026 02:00:00,19/02/2026 12:41:56,19/02/2026 12:41:56,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/9ΠΚ4ΩΕ6-ΕΛΑ,58/2026 ΑΔΕ - Υποβολή σχεδίου προϋπολογισμού Δ...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22957,Ψ66Λ7ΛΨ-8Η2,28987,19/02/2026 02:00:00,19/02/2026 12:33:30,19/02/2026 12:33:30,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/Ψ66Λ7ΛΨ-8Η2,Λήψη μέτρων για τη διάθεση μηχανημάτων έργου (...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
22958,929Δ4653Π8-8ΕΝ,61044,19/02/2026 02:00:00,19/02/2026 11:53:42,19/02/2026 11:53:42,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/929Δ4653Π8-8ΕΝ,Έγκριση αναθεωρημένου χρονοδιαγράμματος της σύ...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22959,ΨΓ8Ρ4653Π8-3ΒΜ,60973,19/02/2026 02:00:00,19/02/2026 11:09:36,19/02/2026 11:09:36,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΨΓ8Ρ4653Π8-3ΒΜ,Ανάθεση σύνταξης μελετών στο Δασαρχείο Σουφλίο...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22960,9ΝΒΡ469ΗΓΥ-ΕΝΣ,848/19-02-2026,19/02/2026 02:00:00,19/02/2026 11:06:50,19/02/2026 11:06:50,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/9ΝΒΡ469ΗΓΥ-ΕΝΣ,ΙΔΙΩΤΙΚΟ ΣΥΜΦΩΝΗΤΙΚΟ ΜΙΣΘΩΣΗΣ ΕΡΓΟΥ - ΠΑΝΤΑΖΗ ...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22961,9ΒΖΞΩΞΗ-ΨΙΩ,903,19/02/2026 02:00:00,19/02/2026 10:54:38,19/02/2026 10:54:38,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/9ΒΖΞΩΞΗ-ΨΙΩ,"Καθορισμός στόχων του Δήμου Παρανεστίου, έτους...",ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22962,Ρ4ΨΜΩΗΝ-Α2Χ,7556 19-02-2026,18/02/2026 02:00:00,19/02/2026 10:20:48,19/02/2026 10:20:48,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/Ρ4ΨΜΩΗΝ-Α2Χ,Απόφαση Ανάληψης Υποχρέωσης Α-912 για :ενίσχυσ...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
22963,Ψ3ΣΡ4653Π8-ΘΛ7,59862,18/02/2026 02:00:00,18/02/2026 14:14:55,18/02/2026 14:14:55,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/Ψ3ΣΡ4653Π8-ΘΛ7,Έγκριση αναθεώρησης τιμών του έργου της σύμβασ...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
22964,ΡΒΓΜΩΕ1-ΟΣ8,1958,18/02/2026 02:00:00,18/02/2026 13:53:07,18/02/2026 13:53:07,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΡΒΓΜΩΕ1-ΟΣ8,Έγκριση Σχεδίου Επιχειρησιακού Προγράμματος Δή...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22965,9ΒΒΖ4653Π8-ΞΑ3,59762,18/02/2026 02:00:00,18/02/2026 13:51:30,18/02/2026 13:51:30,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/9ΒΒΖ4653Π8-ΞΑ3,Έγκριση πρώτου 1ου Ειδικού Απολογισμού και Με...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
22966,650ΓΩΡΗ-Υ1Τ,1060,18/02/2026 02:00:00,18/02/2026 13:49:04,18/02/2026 13:49:04,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/650ΓΩΡΗ-Υ1Τ,Ψήφιση και έγκριση προϋπολογισμού του Δήμου Ζα...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22967,ΡΥΠΞΩΞ2-1ΝΓ,63/18-2-2026,18/02/2026 02:00:00,18/02/2026 13:36:14,18/02/2026 13:36:14,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΡΥΠΞΩΞ2-1ΝΓ,Έγκριση έκθεσης πεπραγμένων Β’ Εξαμήνου 2025 τ...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22968,942ΛΩΞ2-ΟΘΔ,15,17/02/2026 02:00:00,18/02/2026 13:35:47,18/02/2026 13:35:47,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/942ΛΩΞ2-ΟΘΔ,"Έγκριση Προϋπολογισμού του Δήμου, έτους 2026.",ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
22969,ΡΞΞ97ΛΛ-ΑΟΛ,46833/35,05/02/2026 02:00:00,18/02/2026 13:35:09,18/02/2026 13:35:09,PUBLISHED,NaN,https://diavgeia.gov.gr/doc/ΡΞΞ97ΛΛ-ΑΟΛ,Γνωμοδότηση επί της Μελέτης Περιβαλλοντικών Επ...,ΠΡΑΞΗ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [ ]:
import unicodedata

#  ['ΓΕΩΡΓΙΑ, ΔΑΣΟΚΟΜΙΑ ΚΑΙ ΑΛΙΕΙΑ']

keywords = ["πυροπροστ", "αποψιλ", "δασοπροστ", "αντιπυρ", "δασικων πυρκαγιων", "δασικη πυρκαγια", "δημιουργια περιμετρικων ζωνων", "δασικου οδικου δικτυου", "κλαδευσε", "αποκλαδευσ", "απόληψη δασικών προϊόντων", "εκτέλεση εργασιών πρόληψης και αντιμετώπισης εκτάκτων αναγκών από φυσικές – τεχνολογικές καταστροφές", "ΑΠΟΚΑΤΑΣΤΑΣΗ ΒΑΤΟΤΗΤΑΣ ΚΑΘΑΡΙΣΜΟΣ ΤΑΦΡΩΝ", "ΠΡΟΣΤΑΣΙΑΣ ΔΑΣΩΝ", "antiNERO", "αγροτικού οδικού δικτύου", "Προστασία και Αναβάθμιση Δασών", "δασικού παρατηρητηρίου", "πυροφυλακίου", "Ζώνες Δουλείας", "έκτακτης κάρπωσης", "καθαρισμός των υπαρχόντων δρόμων πρόσβασης", "Προϋπολογισμού", "ΠΥΡΑΣΦΑΛΕΙΑΣ", "ΠΕΡΙΜΕΤΡΙΚΩΝ ΖΩΝΩΝ", "ΠΡΟΣΤΑΣΙΑ & ΑΝΑΒΑΘΜΙΣΗ ΔΑΣΩΝ 2024", "ΠΟΛΙΤΙΚΗΣ ΠΡΟΣΤΑΣΙΑΣ", "Έγκριση Επιχειρησιακού Σχεδιασμού", "δασικών πυρκαγιών", "Δημοτικού δάσους", "ΜΙΣΘΩΣΗ ΜΗΧΑΝΗΜΑΤΟΣ ΕΡΓΟΥ", "κλαδοτεμαχιστών", "Αγροτική Οδοποιία", "πυρκαγια", "ΚΑΤΑΣΒΕΣΗ ΔΑΣΙΚΗΣ ΠΥΡΚΑΓΙΑΣ", "ΠΥΡΟΜΕΤΕΩΡΟΛΟΓΙΚΟΥ", "σχεδίων Πολιτικής Προστασίας"]

def remove_tonos(text):
    text = unicodedata.normalize("NFD", str(text))
    return "".join(ch for ch in text if unicodedata.category(ch) != "Mn")

subject_norm = (
    df["subject"]
    .fillna("")
    .astype(str)
    .str.lower()
    .apply(remove_tonos)
)

df["subject_has_keyword"] = subject_norm.str.contains("|".join(keywords), regex=True)

In [69]:
df.to_csv("../data/2026_diavgeia.csv", index=False)

In [76]:
from supabase import create_client
import os
from dotenv import load_dotenv

load_dotenv()

supabase = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_KEY"])

res = supabase.table("fire_incidents").select("*").order("year", desc=False).execute()
print(res.data[0]['year'])
print(res.data[-1]['year'])

2000
2000

In [77]:
res.data

[{'fire_id': 1,
  'year': 2000,
  'date_start': '2000-08-06',
  'date_end': '2000-08-06',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΑΣ',
  'municipality_id': None,
  'area_name': 'ΚΡΥΟΝΕΡΙ',
  'lat': 38.136071,
  'lon': 23.829073,
  'burned_forest_stremata': 3.0,
  'burned_woodland_stremata': 3.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 6.0,
  'burned_total_ha': 0.6,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 2,
  'year': 2000,
  'date_start': '2000-06-14',
  'date_end': '2000-06-14',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΚΑΡΕΑΣ',
  'lat': 37.947499,
  'lon': 23.769539,
  'burned_forest_stremata': 2.0,
  'burned_woodland_stremata': 2.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 4.0,
  'burned_total_ha': 0.4,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 3,
  'year': 2000,
  'date_start': '2000-07-23',
  'date_end': '2000-07-23',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΝΕΚΡΟΤΑΦΕΙΟ ΚΑΙΣΑΡΙΑΝΗΣ',
  'lat': 37.96549,
  'lon': 23.778164,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 2.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 2.0,
  'burned_total_ha': 0.2,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 4,
  'year': 2000,
  'date_start': '2000-04-10',
  'date_end': '2000-04-10',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΔΡΟΣΟΠΟΥΛΟΥ ΑΝΩ ΛΙΟΣΙΑ',
  'lat': 38.005494,
  'lon': 23.735964,
  'burned_forest_stremata': 8.0,
  'burned_woodland_stremata': 0.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 8.0,
  'burned_total_ha': 0.8,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 5,
  'year': 2000,
  'date_start': '2000-07-07',
  'date_end': '2000-07-07',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΑΤΤΑΛΟΣ ΚΑΜΑΤΕΡΟ',
  'lat': 38.054781,
  'lon': 23.699375,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 3.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 3.0,
  'burned_total_ha': 0.3,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 6,
  'year': 2000,
  'date_start': '2000-07-20',
  'date_end': '2000-07-20',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΒΡΑΧΟΣ ΤΟΥ ΕΒΡΑΙΟΥ ΑΝΩ ΛΙΟΣΙΑ',
  'lat': 38.081723,
  'lon': 23.703607,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 2.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 2.0,
  'burned_total_ha': 0.2,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 7,
  'year': 2000,
  'date_start': '2000-06-20',
  'date_end': '2000-06-20',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΝΕΚΡΟΤΑΦΕΙΟ ΜΕΝΙΔΙΟΥ',
  'lat': 38.113785,
  'lon': 23.735759,
  'burned_forest_stremata': 2.0,
  'burned_woodland_stremata': 2.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 4.0,
  'burned_total_ha': 0.4,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 8,
  'year': 2000,
  'date_start': '2000-05-08',
  'date_end': '2000-05-08',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΣΠΗΛΙΑ ΝΤΑΒΕΛΗ Ν.ΠΕΝΤΕΛΗ',
  'lat': 38.070751,
  'lon': 23.877265,
  'burned_forest_stremata': 200.0,
  'burned_woodland_stremata': 800.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 1000.0,
  'burned_total_ha': 100.0,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 9,
  'year': 2000,
  'date_start': '2000-07-29',
  'date_end': '2000-07-29',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΒΑΡΝΑΒΑΣ ΑΤΤΙΚΗΣ',
  'lat': 38.223862,
  'lon': 23.923289,
  'burned_forest_stremata': 5.0,
  'burned_woodland_stremata': 5.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 1.0,
  'burned_total_stremata': 11.0,
  'burned_total_ha': 1.1,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 10,
  'year': 2000,
  'date_start': '2000-07-29',
  'date_end': '2000-09-08',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΓΚΟΥΡΙ ΓΚΛΙΑΤΣΙ ΚΑΛΑΜΟΥ ΑΤΤΙΚΗΣ',
  'lat': 38.284658,
  'lon': 23.863692,
  'burned_forest_stremata': 1400.0,
  'burned_woodland_stremata': 0.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 1400.0,
  'burned_total_ha': 140.0,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 11,
  'year': 2000,
  'date_start': '2000-11-17',
  'date_end': '2000-11-17',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΑΦΙΔΝΑΙ 27 ΧΛΜ ΑΘΗΝΩΝ-ΛΑΜΙΑΣ',
  'lat': 38.01929,
  'lon': 23.7238,
  'burned_forest_stremata': 5.0,
  'burned_woodland_stremata': 0.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 5.0,
  'burned_total_ha': 0.5,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 12,
  'year': 2000,
  'date_start': '2000-09-15',
  'date_end': '2000-09-17',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΑΓΚΩΝΑ ΚΑΛΑΜΟΥ ΑΤΤΙΚΗΣ',
  'lat': 37.993127,
  'lon': 23.732006,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 6.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 4.0,
  'burned_total_stremata': 10.0,
  'burned_total_ha': 1.0,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 13,
  'year': 2000,
  'date_start': '2000-09-07',
  'date_end': '2000-09-07',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΦΡΑΓΜΑ ΜΑΡΑΘΩΝΑ',
  'lat': 38.167152,
  'lon': 23.905588,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 4.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 4.0,
  'burned_total_ha': 0.4,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 14,
  'year': 2000,
  'date_start': '2000-09-19',
  'date_end': '2000-09-20',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΠΕΝΤΕΛΗΣ',
  'lat': 38.04763,
  'lon': 23.869628,
  'burned_forest_stremata': 10.0,
  'burned_woodland_stremata': 0.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 10.0,
  'burned_total_ha': 1.0,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 15,
  'year': 2000,
  'date_start': '2000-07-10',
  'date_end': '2000-07-10',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΔΡΟΣΟΠΗΓΗ ΑΦΙΔΝΩΝ',
  'lat': 38.165892,
  'lon': 23.834248,
  'burned_forest_stremata': 5.0,
  'burned_woodland_stremata': 0.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 5.0,
  'burned_total_ha': 0.5,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 16,
  'year': 2000,
  'date_start': '2000-05-14',
  'date_end': '2000-05-15',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΕΚΑΛΗ',
  'lat': 38.100877,
  'lon': 23.83508,
  'burned_forest_stremata': 1.0,
  'burned_woodland_stremata': 1.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 2.0,
  'burned_total_ha': 0.2,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 17,
  'year': 2000,
  'date_start': '2000-05-24',
  'date_end': '2000-05-24',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': '21 ΧΛΜ ΛΕΩΦ.ΠΑΡΝΗΘΟΣ ΘΡΑΚΟΜΑΚ/ΝΕΣ',
  'lat': 38.119843,
  'lon': 23.734546,
  'burned_forest_stremata': 1.0,
  'burned_woodland_stremata': 1.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 2.0,
  'burned_total_ha': 0.2,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 18,
  'year': 2000,
  'date_start': '2000-09-24',
  'date_end': '2000-09-25',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΚΟΡΑΚΟΒΟΥΝΙ ΙΠΠΟΚΡΑΤΕΙΟΣ ΠΟΛΙΤΕΙΑ',
  'lat': 37.349883,
  'lon': 22.747303,
  'burned_forest_stremata': 2.0,
  'burned_woodland_stremata': 0.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 2.0,
  'burned_total_ha': 0.2,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 19,
  'year': 2000,
  'date_start': '2000-10-30',
  'date_end': None,
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΚΟΥΚΟΥΝΑΡΙ ΣΤΑΜΑΤΑ ΑΤΤΙΚΗΣ',
  'lat': 38.126125,
  'lon': 23.870778,
  'burned_forest_stremata': 1.0,
  'burned_woodland_stremata': 0.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 1.0,
  'burned_total_ha': 0.1,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 20,
  'year': 2000,
  'date_start': '2000-09-08',
  'date_end': '2000-09-08',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΡΕΜΑ ΧΕΛΙΔΟΝΟΥΣ ΚΗΦΙΣΙΑ',
  'lat': 38.087141,
  'lon': 23.799024,
  'burned_forest_stremata': 15.0,
  'burned_woodland_stremata': 0.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 15.0,
  'burned_total_ha': 1.5,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 21,
  'year': 2000,
  'date_start': '2000-07-08',
  'date_end': '2000-08-07',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΕΥΔΑΠ ΜΕΝΙΔΙ',
  'lat': 37.98381,
  'lon': 23.727539,
  'burned_forest_stremata': 3.0,
  'burned_woodland_stremata': 0.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 3.0,
  'burned_total_ha': 0.3,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 22,
  'year': 2000,
  'date_start': '2000-07-28',
  'date_end': '2000-07-28',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΑΜΦΙΑΡΕΙΟ ΚΑΛΑΜΟΥ ΑΤΤΙΚΗΣ',
  'lat': 37.993127,
  'lon': 23.732006,
  'burned_forest_stremata': 400.0,
  'burned_woodland_stremata': 0.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 400.0,
  'burned_total_ha': 40.0,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 23,
  'year': 2000,
  'date_start': '2000-09-28',
  'date_end': '2000-09-29',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΘΗΝΩΝ',
  'municipality_id': None,
  'area_name': 'ΘΕΣΗ ΣΤΡΩΜΑ ΥΜΗΤΤΟΥ ΔΑΣΟΜΕΝΗ ΚΟΡΥΦΗ',
  'lat': 37.965716,
  'lon': 23.747135,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 30.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 30.0,
  'burned_total_ha': 3.0,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 24,
  'year': 2000,
  'date_start': '2000-06-06',
  'date_end': '2000-06-06',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΠΕΙΡΑΙΑ',
  'municipality_id': None,
  'area_name': 'ΛΕΩΦ.ΦΑΝΕΡΩΜΕΝΗΣ ΑΓ.ΓΕΩΡΓΙΟΣ',
  'lat': 37.942986,
  'lon': 23.646983,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 1.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 1.0,
  'burned_total_ha': 0.1,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 25,
  'year': 2000,
  'date_start': '2000-05-31',
  'date_end': '2000-05-31',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΠΕΙΡΑΙΑ',
  'municipality_id': None,
  'area_name': 'ΠΗΛΟΣ ΣΕΛΗΝΙΩΝ',
  'lat': 37.987482,
  'lon': 23.478685,
  'burned_forest_stremata': 2.0,
  'burned_woodland_stremata': 0.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 2.0,
  'burned_total_ha': 0.2,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 26,
  'year': 2000,
  'date_start': '2000-08-20',
  'date_end': '2000-08-20',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΠΕΙΡΑΙΑ',
  'municipality_id': None,
  'area_name': 'ΦΑΝΕΡΩΜΕΝΗ',
  'lat': 37.942986,
  'lon': 23.646983,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 1.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 1.0,
  'burned_total_ha': 0.1,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 27,
  'year': 2000,
  'date_start': '2000-09-26',
  'date_end': '2000-09-26',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΠΕΙΡΑΙΑ',
  'municipality_id': None,
  'area_name': 'ΦΑΝΕΡΩΜΕΝΗ',
  'lat': 37.942986,
  'lon': 23.646983,
  'burned_forest_stremata': 2.0,
  'burned_woodland_stremata': 0.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 2.0,
  'burned_total_ha': 0.2,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 28,
  'year': 2000,
  'date_start': '2000-07-28',
  'date_end': '2000-07-28',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΠΕΙΡΑΙΑ',
  'municipality_id': None,
  'area_name': 'ΝΤΟΥΝΙ ΑΜΠΕΛΑΚΙΩΝ',
  'lat': 37.951056,
  'lon': 23.528022,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 1.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 1.0,
  'burned_total_ha': 0.1,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 29,
  'year': 2000,
  'date_start': '2000-08-26',
  'date_end': '2000-08-26',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΠΕΙΡΑΙΑ',
  'municipality_id': None,
  'area_name': 'ΒΑΣΙΛΙΚΑ',
  'lat': 37.95252,
  'lon': 23.651892,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 5.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 5.0,
  'burned_total_ha': 0.5,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 30,
  'year': 2000,
  'date_start': '2000-06-16',
  'date_end': '2000-06-17',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΠΕΙΡΑΙΑ',
  'municipality_id': None,
  'area_name': 'ΜΠΙΖΑΝΙ',
  'lat': 37.94584,
  'lon': 23.657796,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 200.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 200.0,
  'burned_total_ha': 20.0,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 31,
  'year': 2000,
  'date_start': '2000-08-26',
  'date_end': '2000-08-26',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΙΓΙΝΑΣ',
  'municipality_id': None,
  'area_name': 'ΚΟΥΤΑΛΟΥ-ΒΡΟΧΕΙΑ',
  'lat': 37.746433,
  'lon': 23.428668,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 1.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 1.0,
  'burned_total_ha': 0.1,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 32,
  'year': 2000,
  'date_start': '2000-08-22',
  'date_end': '2000-08-23',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΙΓΙΝΑΣ',
  'municipality_id': None,
  'area_name': 'ΑΙΓΙΝΑ ΠΕΡΙΟΧΕΣ ΒΡΟΧΕΙΑ-ΚΟΥΤΑΛΟΥ-ΑΛΜΠ',
  'lat': 37.740882,
  'lon': 23.501421,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 100.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 200.0,
  'burned_other_stremata': 200.0,
  'burned_total_stremata': 500.0,
  'burned_total_ha': 50.0,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 33,
  'year': 2000,
  'date_start': '2000-09-22',
  'date_end': '2000-09-23',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΙΓΙΝΑΣ',
  'municipality_id': None,
  'area_name': 'ΑΝΙΤΣΑΙΟ',
  'lat': 37.707288,
  'lon': 23.505397,
  'burned_forest_stremata': 0.0,
  'burned_woodland_stremata': 100.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 400.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 500.0,
  'burned_total_ha': 50.0,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 34,
  'year': 2000,
  'date_start': '2000-06-26',
  'date_end': '2000-06-26',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΑΙΓΙΝΑΣ',
  'municipality_id': None,
  'area_name': 'ΑΛΩΝΕΣ',
  'lat': 37.737129,
  'lon': 23.521632,
  'burned_forest_stremata': 2.0,
  'burned_woodland_stremata': 0.0,
  'burned_grove_stremata': 0.0,
  'burned_grassland_stremata': 0.0,
  'burned_other_stremata': 0.0,
  'burned_total_stremata': 2.0,
  'burned_total_ha': 0.2,
  'source': 'fires_geocoded_final_2000_2018.csv',
  'created_at': '2026-02-22T17:41:59.155202+00:00'},
 {'fire_id': 35,
  'year': 2000,
  'date_start': '2000-08-24',
  'date_end': '2000-08-25',
  'nomos': 'ΑΤΤΙΚΗΣ',
  'municipality_raw': 'ΠΕΙΡΑΙΑ',
  'municipality_id': None,
  'area_name': 'ΑΝΩ ΠΕΡΑΜΑ',
  'lat': 37.965609,
  'lon': 23.567709,
  'burned_forest_stremata': 0.0,